// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED   NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_VIDEO_LIKE    NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_VIDEO_COMMENT NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_FOLLOW        NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_VIDEO_LIKE",
		2: "NOTIFICATION_TYPE_VIDEO_COMMENT",
		3: "NOTIFICATION_TYPE_FOLLOW",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":   0,
		"NOTIFICATION_TYPE_VIDEO_LIKE":    1,
		"NOTIFICATION_TYPE_VIDEO_COMMENT": 2,
		"NOTIFICATION_TYPE_FOLLOW":        3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_UNREAD      NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_READ        NotificationStatus = 2
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_UNREAD",
		2: "NOTIFICATION_STATUS_READ",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_UNREAD":      1,
		"NOTIFICATION_STATUS_READ":        2,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

// NotificationInfo 只返回通知关系数据。
// actor 用户资料、视频标题等展示信息由 gateway 批量聚合，避免 Notification RPC 产生 N+1 调用。
type NotificationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationId   uint64                 `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	ActorId          uint64                 `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	NotificationType NotificationType       `protobuf:"varint,3,opt,name=notification_type,json=notificationType,proto3,enum=notification.NotificationType" json:"notification_type,omitempty"`
	VideoId          uint64                 `protobuf:"varint,4,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CommentId        uint64                 `protobuf:"varint,5,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Status           NotificationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=notification.NotificationStatus" json:"status,omitempty"`
	OccurredAt       int64                  `protobuf:"varint,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // Unix milliseconds
	ReadAt           int64                  `protobuf:"varint,8,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`             // Unix milliseconds，未读时为 0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotificationInfo) Reset() {
	*x = NotificationInfo{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationInfo) ProtoMessage() {}

func (x *NotificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationInfo.ProtoReflect.Descriptor instead.
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationInfo) GetNotificationId() uint64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *NotificationInfo) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *NotificationInfo) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationInfo) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *NotificationInfo) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *NotificationInfo) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *NotificationInfo) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *NotificationInfo) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

// receiver_id 必须由 gateway 从 JWT 解析后填入，不能信任前端传入的用户 ID。
// 使用 occurred_at + notification_id 复合游标，保证同毫秒通知稳定翻页。
type ListNotificationsReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId           uint64                 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	CursorOccurredAt     int64                  `protobuf:"varint,2,opt,name=cursor_occurred_at,json=cursorOccurredAt,proto3" json:"cursor_occurred_at,omitempty"`
	CursorNotificationId uint64                 `protobuf:"varint,3,opt,name=cursor_notification_id,json=cursorNotificationId,proto3" json:"cursor_notification_id,omitempty"`
	PageSize             int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListNotificationsReq) Reset() {
	*x = ListNotificationsReq{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsReq) ProtoMessage() {}

func (x *ListNotificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsReq.ProtoReflect.Descriptor instead.
func (*ListNotificationsReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsReq) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ListNotificationsReq) GetCursorOccurredAt() int64 {
	if x != nil {
		return x.CursorOccurredAt
	}
	return 0
}

func (x *ListNotificationsReq) GetCursorNotificationId() uint64 {
	if x != nil {
		return x.CursorNotificationId
	}
	return 0
}

func (x *ListNotificationsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListNotificationsResp struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Notifications            []*NotificationInfo    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextCursorOccurredAt     int64                  `protobuf:"varint,2,opt,name=next_cursor_occurred_at,json=nextCursorOccurredAt,proto3" json:"next_cursor_occurred_at,omitempty"`
	NextCursorNotificationId uint64                 `protobuf:"varint,3,opt,name=next_cursor_notification_id,json=nextCursorNotificationId,proto3" json:"next_cursor_notification_id,omitempty"`
	HasMore                  bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListNotificationsResp) Reset() {
	*x = ListNotificationsResp{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResp) ProtoMessage() {}

func (x *ListNotificationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResp.ProtoReflect.Descriptor instead.
func (*ListNotificationsResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResp) GetNotifications() []*NotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResp) GetNextCursorOccurredAt() int64 {
	if x != nil {
		return x.NextCursorOccurredAt
	}
	return 0
}

func (x *ListNotificationsResp) GetNextCursorNotificationId() uint64 {
	if x != nil {
		return x.NextCursorNotificationId
	}
	return 0
}

func (x *ListNotificationsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetUnreadCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    uint64                 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountReq) Reset() {
	*x = GetUnreadCountReq{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountReq) ProtoMessage() {}

func (x *GetUnreadCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountReq.ProtoReflect.Descriptor instead.
func (*GetUnreadCountReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadCountReq) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

type GetUnreadCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int64                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResp) Reset() {
	*x = GetUnreadCountResp{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResp) ProtoMessage() {}

func (x *GetUnreadCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResp.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetUnreadCountResp) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkNotificationReadReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId     uint64                 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	NotificationId uint64                 `protobuf:"varint,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationReadReq) Reset() {
	*x = MarkNotificationReadReq{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadReq) ProtoMessage() {}

func (x *MarkNotificationReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadReq.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkNotificationReadReq) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *MarkNotificationReadReq) GetNotificationId() uint64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type MarkNotificationReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadResp) Reset() {
	*x = MarkNotificationReadResp{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadResp) ProtoMessage() {}

func (x *MarkNotificationReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadResp.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkNotificationReadResp) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type MarkAllNotificationsReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    uint64                 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadReq) Reset() {
	*x = MarkAllNotificationsReadReq{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadReq) ProtoMessage() {}

func (x *MarkAllNotificationsReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadReq.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAllNotificationsReadReq) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

type MarkAllNotificationsReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangedCount  int64                  `protobuf:"varint,1,opt,name=changed_count,json=changedCount,proto3" json:"changed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsReadResp) Reset() {
	*x = MarkAllNotificationsReadResp{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsReadResp) ProtoMessage() {}

func (x *MarkAllNotificationsReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsReadResp.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsReadResp) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAllNotificationsReadResp) GetChangedCount() int64 {
	if x != nil {
		return x.ChangedCount
	}
	return 0
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"\xd1\x02\n" +
	"\x10NotificationInfo\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x04R\x0enotificationId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\x04R\aactorId\x12K\n" +
	"\x11notification_type\x18\x03 \x01(\x0e2\x1e.notification.NotificationTypeR\x10notificationType\x12\x19\n" +
	"\bvideo_id\x18\x04 \x01(\x04R\avideoId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x05 \x01(\x04R\tcommentId\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .notification.NotificationStatusR\x06status\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\x03R\n" +
	"occurredAt\x12\x17\n" +
	"\aread_at\x18\b \x01(\x03R\x06readAt\"\xb8\x01\n" +
	"\x14ListNotificationsReq\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x04R\n" +
	"receiverId\x12,\n" +
	"\x12cursor_occurred_at\x18\x02 \x01(\x03R\x10cursorOccurredAt\x124\n" +
	"\x16cursor_notification_id\x18\x03 \x01(\x04R\x14cursorNotificationId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xee\x01\n" +
	"\x15ListNotificationsResp\x12D\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1e.notification.NotificationInfoR\rnotifications\x125\n" +
	"\x17next_cursor_occurred_at\x18\x02 \x01(\x03R\x14nextCursorOccurredAt\x12=\n" +
	"\x1bnext_cursor_notification_id\x18\x03 \x01(\x04R\x18nextCursorNotificationId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"4\n" +
	"\x11GetUnreadCountReq\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x04R\n" +
	"receiverId\"7\n" +
	"\x12GetUnreadCountResp\x12!\n" +
	"\funread_count\x18\x01 \x01(\x03R\vunreadCount\"c\n" +
	"\x17MarkNotificationReadReq\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x04R\n" +
	"receiverId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\x04R\x0enotificationId\"4\n" +
	"\x18MarkNotificationReadResp\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\">\n" +
	"\x1bMarkAllNotificationsReadReq\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x04R\n" +
	"receiverId\"C\n" +
	"\x1cMarkAllNotificationsReadResp\x12#\n" +
	"\rchanged_count\x18\x01 \x01(\x03R\fchangedCount*\x9a\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNOTIFICATION_TYPE_VIDEO_LIKE\x10\x01\x12#\n" +
	"\x1fNOTIFICATION_TYPE_VIDEO_COMMENT\x10\x02\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_FOLLOW\x10\x03*w\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_UNREAD\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_READ\x10\x022\x9b\x03\n" +
	"\fNotification\x12\\\n" +
	"\x11ListNotifications\x12\".notification.ListNotificationsReq\x1a#.notification.ListNotificationsResp\x12S\n" +
	"\x0eGetUnreadCount\x12\x1f.notification.GetUnreadCountReq\x1a .notification.GetUnreadCountResp\x12e\n" +
	"\x14MarkNotificationRead\x12%.notification.MarkNotificationReadReq\x1a&.notification.MarkNotificationReadResp\x12q\n" +
	"\x18MarkAllNotificationsRead\x12).notification.MarkAllNotificationsReadReq\x1a*.notification.MarkAllNotificationsReadRespB\x10Z\x0e./notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notification_proto_goTypes = []any{
	(NotificationType)(0),                // 0: notification.NotificationType
	(NotificationStatus)(0),              // 1: notification.NotificationStatus
	(*NotificationInfo)(nil),             // 2: notification.NotificationInfo
	(*ListNotificationsReq)(nil),         // 3: notification.ListNotificationsReq
	(*ListNotificationsResp)(nil),        // 4: notification.ListNotificationsResp
	(*GetUnreadCountReq)(nil),            // 5: notification.GetUnreadCountReq
	(*GetUnreadCountResp)(nil),           // 6: notification.GetUnreadCountResp
	(*MarkNotificationReadReq)(nil),      // 7: notification.MarkNotificationReadReq
	(*MarkNotificationReadResp)(nil),     // 8: notification.MarkNotificationReadResp
	(*MarkAllNotificationsReadReq)(nil),  // 9: notification.MarkAllNotificationsReadReq
	(*MarkAllNotificationsReadResp)(nil), // 10: notification.MarkAllNotificationsReadResp
}
var file_notification_proto_depIdxs = []int32{
	0,  // 0: notification.NotificationInfo.notification_type:type_name -> notification.NotificationType
	1,  // 1: notification.NotificationInfo.status:type_name -> notification.NotificationStatus
	2,  // 2: notification.ListNotificationsResp.notifications:type_name -> notification.NotificationInfo
	3,  // 3: notification.Notification.ListNotifications:input_type -> notification.ListNotificationsReq
	5,  // 4: notification.Notification.GetUnreadCount:input_type -> notification.GetUnreadCountReq
	7,  // 5: notification.Notification.MarkNotificationRead:input_type -> notification.MarkNotificationReadReq
	9,  // 6: notification.Notification.MarkAllNotificationsRead:input_type -> notification.MarkAllNotificationsReadReq
	4,  // 7: notification.Notification.ListNotifications:output_type -> notification.ListNotificationsResp
	6,  // 8: notification.Notification.GetUnreadCount:output_type -> notification.GetUnreadCountResp
	8,  // 9: notification.Notification.MarkNotificationRead:output_type -> notification.MarkNotificationReadResp
	10, // 10: notification.Notification.MarkAllNotificationsRead:output_type -> notification.MarkAllNotificationsReadResp
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
