// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"feedsystem-zero/apps/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh_token",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verification",
				Handler: SendVerificationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: GetProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: UpdateProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/account"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: GetVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:author_id",
					Handler: ListUserVideosHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/video"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: DeleteVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cover",
					Handler: UploadCoverHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/publish",
					Handler: PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/chunk",
					Handler: UploadVideoChunkHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/complete",
					Handler: CompleteVideoUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/init",
					Handler: InitVideoUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/upload/status",
					Handler: VideoUploadStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/video"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/video/:id/comments",
					Handler: ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/video/:id/liked",
					Handler: IsLikedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/interaction"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/comments/:comment_id",
					Handler: DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/likes",
					Handler: ListMyLikedVideosHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/video/:id/comments",
					Handler: PublishCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/video/:id/like",
					Handler: LikeVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/video/:id/like",
					Handler: UnlikeVideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/interaction"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users/:id/followers",
					Handler: ListFollowersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id/following-status",
					Handler: IsFollowingHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id/followings",
					Handler: ListFollowingsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/social"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users/:id/follow",
					Handler: FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:id/follow",
					Handler: UnfollowHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/social"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.OptionalTokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/recommend",
					Handler: GetRecommendFeedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/feed"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/following",
					Handler: GetFollowingFeedHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/feed"),
	)
}
