// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package server

import (
	"context"

	"feedsystem-zero/apps/notification/internal/logic"
	"feedsystem-zero/apps/notification/internal/svc"
	"feedsystem-zero/apps/notification/notification"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	notification.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) ListNotifications(ctx context.Context, in *notification.ListNotificationsReq) (*notification.ListNotificationsResp, error) {
	l := logic.NewListNotificationsLogic(ctx, s.svcCtx)
	return l.ListNotifications(in)
}

func (s *NotificationServer) GetUnreadCount(ctx context.Context, in *notification.GetUnreadCountReq) (*notification.GetUnreadCountResp, error) {
	l := logic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

func (s *NotificationServer) MarkNotificationRead(ctx context.Context, in *notification.MarkNotificationReadReq) (*notification.MarkNotificationReadResp, error) {
	l := logic.NewMarkNotificationReadLogic(ctx, s.svcCtx)
	return l.MarkNotificationRead(in)
}

func (s *NotificationServer) MarkAllNotificationsRead(ctx context.Context, in *notification.MarkAllNotificationsReadReq) (*notification.MarkAllNotificationsReadResp, error) {
	l := logic.NewMarkAllNotificationsReadLogic(ctx, s.svcCtx)
	return l.MarkAllNotificationsRead(in)
}
