// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account.proto

package server

import (
	"context"

	"feedsystem-zero/apps/account/account"
	"feedsystem-zero/apps/account/internal/logic"
	"feedsystem-zero/apps/account/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

// 验证码
func (s *AccountServer) SendVerification(ctx context.Context, in *account.VerificationReq) (*account.VerificationResp, error) {
	l := logic.NewSendVerificationLogic(ctx, s.svcCtx)
	return l.SendVerification(in)
}

// 注册
func (s *AccountServer) Register(ctx context.Context, in *account.RegisterReq) (*account.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 登录
func (s *AccountServer) Login(ctx context.Context, in *account.LoginReq) (*account.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 登出
func (s *AccountServer) Logout(ctx context.Context, in *account.LogoutReq) (*account.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 刷新token
func (s *AccountServer) RefreshToken(ctx context.Context, in *account.RefreshTokenReq) (*account.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 查用户
func (s *AccountServer) GetProfile(ctx context.Context, in *account.GetProfileReq) (*account.GetProfileResp, error) {
	l := logic.NewGetProfileLogic(ctx, s.svcCtx)
	return l.GetProfile(in)
}

// 更新用户信息
func (s *AccountServer) UpdateProfile(ctx context.Context, in *account.UpdateProfileReq) (*account.UpdateProfileResp, error) {
	l := logic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}
