// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: feed.proto

package feedclient

import (
	"context"

	"feedsystem-zero/apps/feed/feed"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedVideoItem        = feed.FeedVideoItem
	GetFollowingFeedReq  = feed.GetFollowingFeedReq
	GetFollowingFeedResp = feed.GetFollowingFeedResp
	GetRecommendFeedReq  = feed.GetRecommendFeedReq
	GetRecommendFeedResp = feed.GetRecommendFeedResp

	Feed interface {
		// 关注流：viewer 关注的所有作者的最新视频，按发布时间倒序
		GetFollowingFeed(ctx context.Context, in *GetFollowingFeedReq, opts ...grpc.CallOption) (*GetFollowingFeedResp, error)
		// 推荐流：当前返回全局最新视频，未登录也可访问
		GetRecommendFeed(ctx context.Context, in *GetRecommendFeedReq, opts ...grpc.CallOption) (*GetRecommendFeedResp, error)
	}

	defaultFeed struct {
		cli zrpc.Client
	}
)

func NewFeed(cli zrpc.Client) Feed {
	return &defaultFeed{
		cli: cli,
	}
}

// 关注流：viewer 关注的所有作者的最新视频，按发布时间倒序
func (m *defaultFeed) GetFollowingFeed(ctx context.Context, in *GetFollowingFeedReq, opts ...grpc.CallOption) (*GetFollowingFeedResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetFollowingFeed(ctx, in, opts...)
}

// 推荐流：当前返回全局最新视频，未登录也可访问
func (m *defaultFeed) GetRecommendFeed(ctx context.Context, in *GetRecommendFeedReq, opts ...grpc.CallOption) (*GetRecommendFeedResp, error) {
	client := feed.NewFeedClient(m.cli.Conn())
	return client.GetRecommendFeed(ctx, in, opts...)
}
