// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/social/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // 主动关注者，必须由 gateway 从 JWT 解析填入
	FollowingId   uint64                 `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // 被关注者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_apps_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowReq) GetFollowingId() uint64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Followed      bool                   `protobuf:"varint,2,opt,name=followed,proto3" json:"followed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_apps_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FollowResp) GetFollowed() bool {
	if x != nil {
		return x.Followed
	}
	return false
}

type UnfollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   uint64                 `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowReq) Reset() {
	*x = UnfollowReq{}
	mi := &file_apps_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowReq) ProtoMessage() {}

func (x *UnfollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowReq.ProtoReflect.Descriptor instead.
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowReq) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *UnfollowReq) GetFollowingId() uint64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type UnfollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Unfollowed    bool                   `protobuf:"varint,2,opt,name=unfollowed,proto3" json:"unfollowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResp) Reset() {
	*x = UnfollowResp{}
	mi := &file_apps_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResp) ProtoMessage() {}

func (x *UnfollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResp.ProtoReflect.Descriptor instead.
func (*UnfollowResp) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UnfollowResp) GetUnfollowed() bool {
	if x != nil {
		return x.Unfollowed
	}
	return false
}

// 查询 follower_id 是否关注了 following_id。
type IsFollowingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   uint64                 `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingReq) Reset() {
	*x = IsFollowingReq{}
	mi := &file_apps_social_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingReq) ProtoMessage() {}

func (x *IsFollowingReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingReq.ProtoReflect.Descriptor instead.
func (*IsFollowingReq) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *IsFollowingReq) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *IsFollowingReq) GetFollowingId() uint64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type IsFollowingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     bool                   `protobuf:"varint,1,opt,name=following,proto3" json:"following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResp) Reset() {
	*x = IsFollowingResp{}
	mi := &file_apps_social_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResp) ProtoMessage() {}

func (x *IsFollowingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResp.ProtoReflect.Descriptor instead.
func (*IsFollowingResp) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *IsFollowingResp) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

// 分页游标：按 id 倒序（最新关注排前面）。
// 首次请求 cursor_id 传 0；后续用上次返回的 next_cursor_id。
type ListFollowersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 被关注者，查询其粉丝列表
	ViewerId      uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 当前查看者，用于后续判断是否互关（本期可忽略）
	CursorId      uint64                 `protobuf:"varint,3,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersReq) Reset() {
	*x = ListFollowersReq{}
	mi := &file_apps_social_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersReq) ProtoMessage() {}

func (x *ListFollowersReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersReq.ProtoReflect.Descriptor instead.
func (*ListFollowersReq) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowersReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowersReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *ListFollowersReq) GetCursorId() uint64 {
	if x != nil {
		return x.CursorId
	}
	return 0
}

func (x *ListFollowersReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowingId   uint64                 `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRelation) Reset() {
	*x = FollowRelation{}
	mi := &file_apps_social_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRelation) ProtoMessage() {}

func (x *FollowRelation) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRelation.ProtoReflect.Descriptor instead.
func (*FollowRelation) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *FollowRelation) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowRelation) GetFollowingId() uint64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

func (x *FollowRelation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListFollowersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*FollowRelation      `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	NextCursorId  uint64                 `protobuf:"varint,2,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersResp) Reset() {
	*x = ListFollowersResp{}
	mi := &file_apps_social_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersResp) ProtoMessage() {}

func (x *ListFollowersResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersResp.ProtoReflect.Descriptor instead.
func (*ListFollowersResp) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *ListFollowersResp) GetFollowers() []*FollowRelation {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *ListFollowersResp) GetNextCursorId() uint64 {
	if x != nil {
		return x.NextCursorId
	}
	return 0
}

func (x *ListFollowersResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListFollowingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 主动关注者，查询其关注列表
	ViewerId      uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	CursorId      uint64                 `protobuf:"varint,3,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsReq) Reset() {
	*x = ListFollowingsReq{}
	mi := &file_apps_social_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsReq) ProtoMessage() {}

func (x *ListFollowingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsReq.ProtoReflect.Descriptor instead.
func (*ListFollowingsReq) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{9}
}

func (x *ListFollowingsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowingsReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *ListFollowingsReq) GetCursorId() uint64 {
	if x != nil {
		return x.CursorId
	}
	return 0
}

func (x *ListFollowingsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListFollowingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followings    []*FollowRelation      `protobuf:"bytes,1,rep,name=followings,proto3" json:"followings,omitempty"`
	NextCursorId  uint64                 `protobuf:"varint,2,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsResp) Reset() {
	*x = ListFollowingsResp{}
	mi := &file_apps_social_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsResp) ProtoMessage() {}

func (x *ListFollowingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsResp.ProtoReflect.Descriptor instead.
func (*ListFollowingsResp) Descriptor() ([]byte, []int) {
	return file_apps_social_social_proto_rawDescGZIP(), []int{10}
}

func (x *ListFollowingsResp) GetFollowings() []*FollowRelation {
	if x != nil {
		return x.Followings
	}
	return nil
}

func (x *ListFollowingsResp) GetNextCursorId() uint64 {
	if x != nil {
		return x.NextCursorId
	}
	return 0
}

func (x *ListFollowingsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_apps_social_social_proto protoreflect.FileDescriptor

const file_apps_social_social_proto_rawDesc = "" +
	"\n" +
	"\x18apps/social/social.proto\x12\x06social\"O\n" +
	"\tFollowReq\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x04R\vfollowingId\":\n" +
	"\n" +
	"FollowResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1a\n" +
	"\bfollowed\x18\x02 \x01(\bR\bfollowed\"Q\n" +
	"\vUnfollowReq\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x04R\vfollowingId\"@\n" +
	"\fUnfollowResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1e\n" +
	"\n" +
	"unfollowed\x18\x02 \x01(\bR\n" +
	"unfollowed\"T\n" +
	"\x0eIsFollowingReq\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x04R\vfollowingId\"/\n" +
	"\x0fIsFollowingResp\x12\x1c\n" +
	"\tfollowing\x18\x01 \x01(\bR\tfollowing\"\x82\x01\n" +
	"\x10ListFollowersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\x12\x1b\n" +
	"\tcursor_id\x18\x03 \x01(\x04R\bcursorId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"s\n" +
	"\x0eFollowRelation\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x04R\vfollowingId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x11ListFollowersResp\x124\n" +
	"\tfollowers\x18\x01 \x03(\v2\x16.social.FollowRelationR\tfollowers\x12$\n" +
	"\x0enext_cursor_id\x18\x02 \x01(\x04R\fnextCursorId\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x83\x01\n" +
	"\x11ListFollowingsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\x12\x1b\n" +
	"\tcursor_id\x18\x03 \x01(\x04R\bcursorId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x8d\x01\n" +
	"\x12ListFollowingsResp\x126\n" +
	"\n" +
	"followings\x18\x01 \x03(\v2\x16.social.FollowRelationR\n" +
	"followings\x12$\n" +
	"\x0enext_cursor_id\x18\x02 \x01(\x04R\fnextCursorId\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xbf\x02\n" +
	"\x06Social\x12/\n" +
	"\x06Follow\x12\x11.social.FollowReq\x1a\x12.social.FollowResp\x125\n" +
	"\bUnfollow\x12\x13.social.UnfollowReq\x1a\x14.social.UnfollowResp\x12>\n" +
	"\vIsFollowing\x12\x16.social.IsFollowingReq\x1a\x17.social.IsFollowingResp\x12D\n" +
	"\rListFollowers\x12\x18.social.ListFollowersReq\x1a\x19.social.ListFollowersResp\x12G\n" +
	"\x0eListFollowings\x12\x19.social.ListFollowingsReq\x1a\x1a.social.ListFollowingsRespB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_apps_social_social_proto_rawDescOnce sync.Once
	file_apps_social_social_proto_rawDescData []byte
)

func file_apps_social_social_proto_rawDescGZIP() []byte {
	file_apps_social_social_proto_rawDescOnce.Do(func() {
		file_apps_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_social_social_proto_rawDesc), len(file_apps_social_social_proto_rawDesc)))
	})
	return file_apps_social_social_proto_rawDescData
}

var file_apps_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apps_social_social_proto_goTypes = []any{
	(*FollowReq)(nil),          // 0: social.FollowReq
	(*FollowResp)(nil),         // 1: social.FollowResp
	(*UnfollowReq)(nil),        // 2: social.UnfollowReq
	(*UnfollowResp)(nil),       // 3: social.UnfollowResp
	(*IsFollowingReq)(nil),     // 4: social.IsFollowingReq
	(*IsFollowingResp)(nil),    // 5: social.IsFollowingResp
	(*ListFollowersReq)(nil),   // 6: social.ListFollowersReq
	(*FollowRelation)(nil),     // 7: social.FollowRelation
	(*ListFollowersResp)(nil),  // 8: social.ListFollowersResp
	(*ListFollowingsReq)(nil),  // 9: social.ListFollowingsReq
	(*ListFollowingsResp)(nil), // 10: social.ListFollowingsResp
}
var file_apps_social_social_proto_depIdxs = []int32{
	7,  // 0: social.ListFollowersResp.followers:type_name -> social.FollowRelation
	7,  // 1: social.ListFollowingsResp.followings:type_name -> social.FollowRelation
	0,  // 2: social.Social.Follow:input_type -> social.FollowReq
	2,  // 3: social.Social.Unfollow:input_type -> social.UnfollowReq
	4,  // 4: social.Social.IsFollowing:input_type -> social.IsFollowingReq
	6,  // 5: social.Social.ListFollowers:input_type -> social.ListFollowersReq
	9,  // 6: social.Social.ListFollowings:input_type -> social.ListFollowingsReq
	1,  // 7: social.Social.Follow:output_type -> social.FollowResp
	3,  // 8: social.Social.Unfollow:output_type -> social.UnfollowResp
	5,  // 9: social.Social.IsFollowing:output_type -> social.IsFollowingResp
	8,  // 10: social.Social.ListFollowers:output_type -> social.ListFollowersResp
	10, // 11: social.Social.ListFollowings:output_type -> social.ListFollowingsResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_apps_social_social_proto_init() }
func file_apps_social_social_proto_init() {
	if File_apps_social_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_social_social_proto_rawDesc), len(file_apps_social_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_social_social_proto_goTypes,
		DependencyIndexes: file_apps_social_social_proto_depIdxs,
		MessageInfos:      file_apps_social_social_proto_msgTypes,
	}.Build()
	File_apps_social_social_proto = out.File
	file_apps_social_social_proto_goTypes = nil
	file_apps_social_social_proto_depIdxs = nil
}
