// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_Follow_FullMethodName           = "/social.Social/Follow"
	Social_Unfollow_FullMethodName         = "/social.Social/Unfollow"
	Social_IsFollowing_FullMethodName      = "/social.Social/IsFollowing"
	Social_ListFollowers_FullMethodName    = "/social.Social/ListFollowers"
	Social_ListFollowings_FullMethodName   = "/social.Social/ListFollowings"
	Social_BatchIsFollowing_FullMethodName = "/social.Social/BatchIsFollowing"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 社交关系服务
type SocialClient interface {
	// 关注
	Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	// 取关
	Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
	// 判断是否关注
	IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error)
	// 展示粉丝
	ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error)
	// 展示关注
	ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error)
	// 批量获取关注信息
	BatchIsFollowing(ctx context.Context, in *BatchIsFollowingReq, opts ...grpc.CallOption) (*BatchIsFollowingResp, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Social_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowResp)
	err := c.cc.Invoke(ctx, Social_Unfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowingResp)
	err := c.cc.Invoke(ctx, Social_IsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowersResp)
	err := c.cc.Invoke(ctx, Social_ListFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowingsResp)
	err := c.cc.Invoke(ctx, Social_ListFollowings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) BatchIsFollowing(ctx context.Context, in *BatchIsFollowingReq, opts ...grpc.CallOption) (*BatchIsFollowingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIsFollowingResp)
	err := c.cc.Invoke(ctx, Social_BatchIsFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
//
// 社交关系服务
type SocialServer interface {
	// 关注
	Follow(context.Context, *FollowReq) (*FollowResp, error)
	// 取关
	Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error)
	// 判断是否关注
	IsFollowing(context.Context, *IsFollowingReq) (*IsFollowingResp, error)
	// 展示粉丝
	ListFollowers(context.Context, *ListFollowersReq) (*ListFollowersResp, error)
	// 展示关注
	ListFollowings(context.Context, *ListFollowingsReq) (*ListFollowingsResp, error)
	// 批量获取关注信息
	BatchIsFollowing(context.Context, *BatchIsFollowingReq) (*BatchIsFollowingResp, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) Follow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedSocialServer) Unfollow(context.Context, *UnfollowReq) (*UnfollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unfollow not implemented")
}
func (UnimplementedSocialServer) IsFollowing(context.Context, *IsFollowingReq) (*IsFollowingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFollowing not implemented")
}
func (UnimplementedSocialServer) ListFollowers(context.Context, *ListFollowersReq) (*ListFollowersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowers not implemented")
}
func (UnimplementedSocialServer) ListFollowings(context.Context, *ListFollowingsReq) (*ListFollowingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowings not implemented")
}
func (UnimplementedSocialServer) BatchIsFollowing(context.Context, *BatchIsFollowingReq) (*BatchIsFollowingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchIsFollowing not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call panics, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Follow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_Unfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).Unfollow(ctx, req.(*UnfollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_IsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).IsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_IsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).IsFollowing(ctx, req.(*IsFollowingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListFollowers(ctx, req.(*ListFollowersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_ListFollowings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).ListFollowings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_ListFollowings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).ListFollowings(ctx, req.(*ListFollowingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_BatchIsFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIsFollowingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).BatchIsFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_BatchIsFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).BatchIsFollowing(ctx, req.(*BatchIsFollowingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Follow",
			Handler:    _Social_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _Social_Unfollow_Handler,
		},
		{
			MethodName: "IsFollowing",
			Handler:    _Social_IsFollowing_Handler,
		},
		{
			MethodName: "ListFollowers",
			Handler:    _Social_ListFollowers_Handler,
		},
		{
			MethodName: "ListFollowings",
			Handler:    _Social_ListFollowings_Handler,
		},
		{
			MethodName: "BatchIsFollowing",
			Handler:    _Social_BatchIsFollowing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
