// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package server

import (
	"context"

	"feedsystem-zero/apps/interaction/interaction"
	"feedsystem-zero/apps/interaction/internal/logic"
	"feedsystem-zero/apps/interaction/internal/svc"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	interaction.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) LikeVideo(ctx context.Context, in *interaction.LikeVideoReq) (*interaction.LikeVideoResp, error) {
	l := logic.NewLikeVideoLogic(ctx, s.svcCtx)
	return l.LikeVideo(in)
}

func (s *InteractionServer) UnlikeVideo(ctx context.Context, in *interaction.UnlikeVideoReq) (*interaction.UnlikeVideoResp, error) {
	l := logic.NewUnlikeVideoLogic(ctx, s.svcCtx)
	return l.UnlikeVideo(in)
}

func (s *InteractionServer) IsLiked(ctx context.Context, in *interaction.IsLikedReq) (*interaction.IsLikedResp, error) {
	l := logic.NewIsLikedLogic(ctx, s.svcCtx)
	return l.IsLiked(in)
}

func (s *InteractionServer) ListMyLikedVideos(ctx context.Context, in *interaction.ListMyLikedVideosReq) (*interaction.ListMyLikedVideosResp, error) {
	l := logic.NewListMyLikedVideosLogic(ctx, s.svcCtx)
	return l.ListMyLikedVideos(in)
}

func (s *InteractionServer) PublishComment(ctx context.Context, in *interaction.PublishCommentReq) (*interaction.PublishCommentResp, error) {
	l := logic.NewPublishCommentLogic(ctx, s.svcCtx)
	return l.PublishComment(in)
}

func (s *InteractionServer) DeleteComment(ctx context.Context, in *interaction.DeleteCommentReq) (*interaction.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *InteractionServer) ListComments(ctx context.Context, in *interaction.ListCommentsReq) (*interaction.ListCommentsResp, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

func (s *InteractionServer) BatchGetVideoStats(ctx context.Context, in *interaction.BatchGetVideoStatsReq) (*interaction.BatchGetVideoStatsResp, error) {
	l := logic.NewBatchGetVideoStatsLogic(ctx, s.svcCtx)
	return l.BatchGetVideoStats(in)
}

func (s *InteractionServer) FlushLikeEvents(ctx context.Context, in *interaction.FlushLikeEventsReq) (*interaction.FlushLikeEventsResp, error) {
	l := logic.NewFlushLikeEventsLogic(ctx, s.svcCtx)
	return l.FlushLikeEvents(in)
}

func (s *InteractionServer) FlushCommentEvents(ctx context.Context, in *interaction.FlushCommentEventsReq) (*interaction.FlushCommentEventsResp, error) {
	l := logic.NewFlushCommentEventsLogic(ctx, s.svcCtx)
	return l.FlushCommentEvents(in)
}

func (s *InteractionServer) RebuildVideoInteractionStats(ctx context.Context, in *interaction.RebuildVideoInteractionStatsReq) (*interaction.RebuildVideoInteractionStatsResp, error) {
	l := logic.NewRebuildVideoInteractionStatsLogic(ctx, s.svcCtx)
	return l.RebuildVideoInteractionStats(in)
}
