// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package videoclient

import (
	"context"

	"feedsystem-zero/apps/video/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetVideosReq  = video.BatchGetVideosReq
	BatchGetVideosResp = video.BatchGetVideosResp
	DeleteVideoReq     = video.DeleteVideoReq
	DeleteVideoResp    = video.DeleteVideoResp
	GetVideoReq        = video.GetVideoReq
	GetVideoResp       = video.GetVideoResp
	ListUserVideosReq  = video.ListUserVideosReq
	ListUserVideosResp = video.ListUserVideosResp
	PublishVideoReq    = video.PublishVideoReq
	PublishVideoResp   = video.PublishVideoResp
	VideoInfo          = video.VideoInfo

	Video interface {
		// 发布视频
		PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error)
		// 获取视频详情
		GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error)
		// 批量获取视频实体
		BatchGetVideos(ctx context.Context, in *BatchGetVideosReq, opts ...grpc.CallOption) (*BatchGetVideosResp, error)
		// 获取作者发布的视频列表
		ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListUserVideosResp, error)
		// 删除视频
		DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 发布视频
func (m *defaultVideo) PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

// 获取视频详情
func (m *defaultVideo) GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

// 批量获取视频实体
func (m *defaultVideo) BatchGetVideos(ctx context.Context, in *BatchGetVideosReq, opts ...grpc.CallOption) (*BatchGetVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.BatchGetVideos(ctx, in, opts...)
}

// 获取作者发布的视频列表
func (m *defaultVideo) ListUserVideos(ctx context.Context, in *ListUserVideosReq, opts ...grpc.CallOption) (*ListUserVideosResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.ListUserVideos(ctx, in, opts...)
}

// 删除视频
func (m *defaultVideo) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.DeleteVideo(ctx, in, opts...)
}
