// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: interaction.proto

package interactionclient

import (
	"context"

	"feedsystem-zero/apps/interaction/interaction"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetVideoStatsReq            = interaction.BatchGetVideoStatsReq
	BatchGetVideoStatsResp           = interaction.BatchGetVideoStatsResp
	CommentEvent                     = interaction.CommentEvent
	CommentInfo                      = interaction.CommentInfo
	DeleteCommentReq                 = interaction.DeleteCommentReq
	DeleteCommentResp                = interaction.DeleteCommentResp
	FlushCommentEventsReq            = interaction.FlushCommentEventsReq
	FlushCommentEventsResp           = interaction.FlushCommentEventsResp
	FlushLikeEventsReq               = interaction.FlushLikeEventsReq
	FlushLikeEventsResp              = interaction.FlushLikeEventsResp
	IsLikedReq                       = interaction.IsLikedReq
	IsLikedResp                      = interaction.IsLikedResp
	LikeEvent                        = interaction.LikeEvent
	LikeVideoReq                     = interaction.LikeVideoReq
	LikeVideoResp                    = interaction.LikeVideoResp
	LikedVideoItem                   = interaction.LikedVideoItem
	ListCommentsReq                  = interaction.ListCommentsReq
	ListCommentsResp                 = interaction.ListCommentsResp
	ListMyLikedVideosReq             = interaction.ListMyLikedVideosReq
	ListMyLikedVideosResp            = interaction.ListMyLikedVideosResp
	PublishCommentReq                = interaction.PublishCommentReq
	PublishCommentResp               = interaction.PublishCommentResp
	RebuildVideoInteractionStatsReq  = interaction.RebuildVideoInteractionStatsReq
	RebuildVideoInteractionStatsResp = interaction.RebuildVideoInteractionStatsResp
	UnlikeVideoReq                   = interaction.UnlikeVideoReq
	UnlikeVideoResp                  = interaction.UnlikeVideoResp
	VideoInteractionStats            = interaction.VideoInteractionStats

	Interaction interface {
		LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error)
		UnlikeVideo(ctx context.Context, in *UnlikeVideoReq, opts ...grpc.CallOption) (*UnlikeVideoResp, error)
		IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error)
		ListMyLikedVideos(ctx context.Context, in *ListMyLikedVideosReq, opts ...grpc.CallOption) (*ListMyLikedVideosResp, error)
		PublishComment(ctx context.Context, in *PublishCommentReq, opts ...grpc.CallOption) (*PublishCommentResp, error)
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
		BatchGetVideoStats(ctx context.Context, in *BatchGetVideoStatsReq, opts ...grpc.CallOption) (*BatchGetVideoStatsResp, error)
		FlushLikeEvents(ctx context.Context, in *FlushLikeEventsReq, opts ...grpc.CallOption) (*FlushLikeEventsResp, error)
		FlushCommentEvents(ctx context.Context, in *FlushCommentEventsReq, opts ...grpc.CallOption) (*FlushCommentEventsResp, error)
		RebuildVideoInteractionStats(ctx context.Context, in *RebuildVideoInteractionStatsReq, opts ...grpc.CallOption) (*RebuildVideoInteractionStatsResp, error)
	}

	defaultInteraction struct {
		cli zrpc.Client
	}
)

func NewInteraction(cli zrpc.Client) Interaction {
	return &defaultInteraction{
		cli: cli,
	}
}

func (m *defaultInteraction) LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.LikeVideo(ctx, in, opts...)
}

func (m *defaultInteraction) UnlikeVideo(ctx context.Context, in *UnlikeVideoReq, opts ...grpc.CallOption) (*UnlikeVideoResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.UnlikeVideo(ctx, in, opts...)
}

func (m *defaultInteraction) IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.IsLiked(ctx, in, opts...)
}

func (m *defaultInteraction) ListMyLikedVideos(ctx context.Context, in *ListMyLikedVideosReq, opts ...grpc.CallOption) (*ListMyLikedVideosResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.ListMyLikedVideos(ctx, in, opts...)
}

func (m *defaultInteraction) PublishComment(ctx context.Context, in *PublishCommentReq, opts ...grpc.CallOption) (*PublishCommentResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.PublishComment(ctx, in, opts...)
}

func (m *defaultInteraction) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultInteraction) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.ListComments(ctx, in, opts...)
}

func (m *defaultInteraction) BatchGetVideoStats(ctx context.Context, in *BatchGetVideoStatsReq, opts ...grpc.CallOption) (*BatchGetVideoStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.BatchGetVideoStats(ctx, in, opts...)
}

func (m *defaultInteraction) FlushLikeEvents(ctx context.Context, in *FlushLikeEventsReq, opts ...grpc.CallOption) (*FlushLikeEventsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.FlushLikeEvents(ctx, in, opts...)
}

func (m *defaultInteraction) FlushCommentEvents(ctx context.Context, in *FlushCommentEventsReq, opts ...grpc.CallOption) (*FlushCommentEventsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.FlushCommentEvents(ctx, in, opts...)
}

func (m *defaultInteraction) RebuildVideoInteractionStats(ctx context.Context, in *RebuildVideoInteractionStatsReq, opts ...grpc.CallOption) (*RebuildVideoInteractionStatsResp, error) {
	client := interaction.NewInteractionClient(m.cli.Conn())
	return client.RebuildVideoInteractionStats(ctx, in, opts...)
}
