package scenario

import (
	"context"
	"fmt"
	"log"
	"sync/atomic"
	"time"

	"feedsystem-zero/tests/internal/httpclient"
	"feedsystem-zero/tests/internal/loadgen"
	"feedsystem-zero/tests/internal/testconfig"
)

// PublishVideoScenario exercises POST /video/publish. Every request must
// carry a unique request_id (idempotency key) and a play_url that already
// exists in file_assets — the seed tool created a small bucket of such
// assets for exactly this reason.
type PublishVideoScenario struct {
	client        *httpclient.Client
	tokens        *tokenPool
	playURLPool   []string
	coverURLPool  []string
	requestSerial atomic.Int64
}

func (s *PublishVideoScenario) Name() string { return "publish_video" }

func (s *PublishVideoScenario) Setup(ctx context.Context, f testconfig.LoadTestFlags) error {
	db, err := openMySQL(f.MysqlDSN)
	if err != nil {
		return err
	}
	usernames, err := sampleUsernames(ctx, db, f.LoginPoolSize)
	if err != nil {
		return err
	}
	log.Printf("[publish_video] sampled %d users, logging in...", len(usernames))
	tokens, err := prepareTokens(ctx, f.BaseURL, f.Timeout, usernames, f.LoginPoolSize)
	if err != nil {
		return err
	}
	s.tokens = tokens

	// 加载 seed 创建的真实磁盘占位资源，发布仍会经过 video-rpc 的行锁与磁盘校验。
	var playURLs []string
	if err := db.WithContext(ctx).
		Raw("SELECT url FROM file_assets WHERE file_hash LIKE 'seed-video-hash-%' AND file_type='video'").
		Scan(&playURLs).Error; err != nil {
		return err
	}
	var coverURLs []string
	if err := db.WithContext(ctx).
		Raw("SELECT url FROM file_assets WHERE file_hash LIKE 'seed-cover-hash-%' AND file_type='cover'").
		Scan(&coverURLs).Error; err != nil {
		return err
	}
	if len(playURLs) == 0 || len(coverURLs) == 0 {
		return fmt.Errorf("no seed file_assets; run cmd/seed first")
	}
	s.playURLPool = playURLs
	s.coverURLPool = coverURLs
	log.Printf("[publish_video] using %d video and %d cover placeholder assets", len(playURLs), len(coverURLs))

	s.client = httpclient.New(f.BaseURL, f.Timeout)
	return nil
}

func (s *PublishVideoScenario) Op() loadgen.Op {
	// Baseline for unique request_ids: startTime-nanos + monotonic counter,
	// so each publish maps to exactly one row in the videos table.
	startNanos := time.Now().UnixNano()
	return func(ctx context.Context, workerID int) error {
		rng := perWorkerRand(workerID)
		token, _ := s.tokens.pick(rng.Int())
		serial := s.requestSerial.Add(1)

		playURL := s.playURLPool[rng.Intn(len(s.playURLPool))]
		coverURL := s.coverURLPool[rng.Intn(len(s.coverURLPool))]
		reqID := fmt.Sprintf("loadtest-%d-%d", startNanos, serial)

		ctx = httpclient.WithToken(ctx, token)
		if _, err := s.client.PublishVideo(ctx, httpclient.PublishVideoReq{
			Title:       fmt.Sprintf("loadtest video %d", serial),
			Description: "auto-generated by tests/loadtest",
			PlayURL:     playURL,
			CoverURL:    coverURL,
			RequestID:   reqID,
		}); err != nil {
			return fmt.Errorf("publish: %w", err)
		}
		return nil
	}
}
