// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: interaction.proto

package interaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Internal event types for job/worker calls.
type LikeAction int32

const (
	LikeAction_LIKE_ACTION_UNKNOWN LikeAction = 0
	LikeAction_LIKE_ACTION_LIKE    LikeAction = 1
	LikeAction_LIKE_ACTION_UNLIKE  LikeAction = 2
)

// Enum value maps for LikeAction.
var (
	LikeAction_name = map[int32]string{
		0: "LIKE_ACTION_UNKNOWN",
		1: "LIKE_ACTION_LIKE",
		2: "LIKE_ACTION_UNLIKE",
	}
	LikeAction_value = map[string]int32{
		"LIKE_ACTION_UNKNOWN": 0,
		"LIKE_ACTION_LIKE":    1,
		"LIKE_ACTION_UNLIKE":  2,
	}
)

func (x LikeAction) Enum() *LikeAction {
	p := new(LikeAction)
	*p = x
	return p
}

func (x LikeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LikeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_interaction_proto_enumTypes[0].Descriptor()
}

func (LikeAction) Type() protoreflect.EnumType {
	return &file_interaction_proto_enumTypes[0]
}

func (x LikeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LikeAction.Descriptor instead.
func (LikeAction) EnumDescriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

type CommentAction int32

const (
	CommentAction_COMMENT_ACTION_UNKNOWN CommentAction = 0
	CommentAction_COMMENT_ACTION_CREATE  CommentAction = 1
	CommentAction_COMMENT_ACTION_DELETE  CommentAction = 2
)

// Enum value maps for CommentAction.
var (
	CommentAction_name = map[int32]string{
		0: "COMMENT_ACTION_UNKNOWN",
		1: "COMMENT_ACTION_CREATE",
		2: "COMMENT_ACTION_DELETE",
	}
	CommentAction_value = map[string]int32{
		"COMMENT_ACTION_UNKNOWN": 0,
		"COMMENT_ACTION_CREATE":  1,
		"COMMENT_ACTION_DELETE":  2,
	}
)

func (x CommentAction) Enum() *CommentAction {
	p := new(CommentAction)
	*p = x
	return p
}

func (x CommentAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentAction) Descriptor() protoreflect.EnumDescriptor {
	return file_interaction_proto_enumTypes[1].Descriptor()
}

func (CommentAction) Type() protoreflect.EnumType {
	return &file_interaction_proto_enumTypes[1]
}

func (x CommentAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentAction.Descriptor instead.
func (CommentAction) EnumDescriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

// CommentInfo is returned by comment write/list APIs.
// can_delete should be computed by service from requester/user ownership.
type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix milliseconds
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix milliseconds
	CanDelete     bool                   `protobuf:"varint,8,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *CommentInfo) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentInfo) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CommentInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CommentInfo) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

// LikeVideo should be idempotent:
// repeated like by the same user on the same video returns liked=true.
type LikeVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoReq) Reset() {
	*x = LikeVideoReq{}
	mi := &file_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoReq) ProtoMessage() {}

func (x *LikeVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoReq.ProtoReflect.Descriptor instead.
func (*LikeVideoReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeVideoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type LikeVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Liked         bool                   `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`
	LikesCount    int64                  `protobuf:"varint,3,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResp) Reset() {
	*x = LikeVideoResp{}
	mi := &file_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResp) ProtoMessage() {}

func (x *LikeVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResp.ProtoReflect.Descriptor instead.
func (*LikeVideoResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *LikeVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LikeVideoResp) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *LikeVideoResp) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

// UnlikeVideo should be idempotent:
// repeated unlike by the same user on the same video returns liked=false.
type UnlikeVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoReq) Reset() {
	*x = UnlikeVideoReq{}
	mi := &file_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoReq) ProtoMessage() {}

func (x *UnlikeVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoReq.ProtoReflect.Descriptor instead.
func (*UnlikeVideoReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeVideoReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlikeVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type UnlikeVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Liked         bool                   `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`
	LikesCount    int64                  `protobuf:"varint,3,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoResp) Reset() {
	*x = UnlikeVideoResp{}
	mi := &file_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoResp) ProtoMessage() {}

func (x *UnlikeVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoResp.ProtoReflect.Descriptor instead.
func (*UnlikeVideoResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *UnlikeVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UnlikeVideoResp) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *UnlikeVideoResp) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type IsLikedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedReq) Reset() {
	*x = IsLikedReq{}
	mi := &file_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedReq) ProtoMessage() {}

func (x *IsLikedReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedReq.ProtoReflect.Descriptor instead.
func (*IsLikedReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *IsLikedReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsLikedReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type IsLikedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedResp) Reset() {
	*x = IsLikedResp{}
	mi := &file_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedResp) ProtoMessage() {}

func (x *IsLikedResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedResp.ProtoReflect.Descriptor instead.
func (*IsLikedResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *IsLikedResp) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type LikedVideoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeId        uint64                 `protobuf:"varint,1,opt,name=like_id,json=likeId,proto3" json:"like_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	LikedAt       int64                  `protobuf:"varint,3,opt,name=liked_at,json=likedAt,proto3" json:"liked_at,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikedVideoItem) Reset() {
	*x = LikedVideoItem{}
	mi := &file_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikedVideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikedVideoItem) ProtoMessage() {}

func (x *LikedVideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikedVideoItem.ProtoReflect.Descriptor instead.
func (*LikedVideoItem) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *LikedVideoItem) GetLikeId() uint64 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

func (x *LikedVideoItem) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikedVideoItem) GetLikedAt() int64 {
	if x != nil {
		return x.LikedAt
	}
	return 0
}

// ListMyLikedVideos returns ids, not hydrated video details.
// Gateway can call video-rpc/feed-rpc to hydrate details later.
type ListMyLikedVideosReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,2,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"`
	CursorLikeId    uint64                 `protobuf:"varint,3,opt,name=cursor_like_id,json=cursorLikeId,proto3" json:"cursor_like_id,omitempty"`
	PageSize        int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMyLikedVideosReq) Reset() {
	*x = ListMyLikedVideosReq{}
	mi := &file_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyLikedVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyLikedVideosReq) ProtoMessage() {}

func (x *ListMyLikedVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyLikedVideosReq.ProtoReflect.Descriptor instead.
func (*ListMyLikedVideosReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *ListMyLikedVideosReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListMyLikedVideosReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListMyLikedVideosReq) GetCursorLikeId() uint64 {
	if x != nil {
		return x.CursorLikeId
	}
	return 0
}

func (x *ListMyLikedVideosReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMyLikedVideosResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LikedVideos         []*LikedVideoItem      `protobuf:"bytes,1,rep,name=liked_videos,json=likedVideos,proto3" json:"liked_videos,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorLikeId    uint64                 `protobuf:"varint,3,opt,name=next_cursor_like_id,json=nextCursorLikeId,proto3" json:"next_cursor_like_id,omitempty"`
	HasMore             bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListMyLikedVideosResp) Reset() {
	*x = ListMyLikedVideosResp{}
	mi := &file_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyLikedVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyLikedVideosResp) ProtoMessage() {}

func (x *ListMyLikedVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyLikedVideosResp.ProtoReflect.Descriptor instead.
func (*ListMyLikedVideosResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *ListMyLikedVideosResp) GetLikedVideos() []*LikedVideoItem {
	if x != nil {
		return x.LikedVideos
	}
	return nil
}

func (x *ListMyLikedVideosResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListMyLikedVideosResp) GetNextCursorLikeId() uint64 {
	if x != nil {
		return x.NextCursorLikeId
	}
	return 0
}

func (x *ListMyLikedVideosResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// request_id is optional but useful for idempotency from gateway/client.
type PublishCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCommentReq) Reset() {
	*x = PublishCommentReq{}
	mi := &file_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommentReq) ProtoMessage() {}

func (x *PublishCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommentReq.ProtoReflect.Descriptor instead.
func (*PublishCommentReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *PublishCommentReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishCommentReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PublishCommentReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *PublishCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PublishCommentReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PublishCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Comment       *CommentInfo           `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	CommentsCount int64                  `protobuf:"varint,3,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCommentResp) Reset() {
	*x = PublishCommentResp{}
	mi := &file_interaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommentResp) ProtoMessage() {}

func (x *PublishCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommentResp.ProtoReflect.Descriptor instead.
func (*PublishCommentResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *PublishCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PublishCommentResp) GetComment() *CommentInfo {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *PublishCommentResp) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_interaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCommentReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentReq) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CommentsCount int64                  `protobuf:"varint,3,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_interaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCommentResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteCommentResp) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteCommentResp) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

type ListCommentsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ViewerId        uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,3,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"`
	CursorCommentId uint64                 `protobuf:"varint,4,opt,name=cursor_comment_id,json=cursorCommentId,proto3" json:"cursor_comment_id,omitempty"`
	PageSize        int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCommentsReq) Reset() {
	*x = ListCommentsReq{}
	mi := &file_interaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsReq) ProtoMessage() {}

func (x *ListCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsReq.ProtoReflect.Descriptor instead.
func (*ListCommentsReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{14}
}

func (x *ListCommentsReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *ListCommentsReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *ListCommentsReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListCommentsReq) GetCursorCommentId() uint64 {
	if x != nil {
		return x.CursorCommentId
	}
	return 0
}

func (x *ListCommentsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCommentsResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Comments            []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorCommentId uint64                 `protobuf:"varint,3,opt,name=next_cursor_comment_id,json=nextCursorCommentId,proto3" json:"next_cursor_comment_id,omitempty"`
	HasMore             bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListCommentsResp) Reset() {
	*x = ListCommentsResp{}
	mi := &file_interaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResp) ProtoMessage() {}

func (x *ListCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResp.ProtoReflect.Descriptor instead.
func (*ListCommentsResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{15}
}

func (x *ListCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListCommentsResp) GetNextCursorCommentId() uint64 {
	if x != nil {
		return x.NextCursorCommentId
	}
	return 0
}

func (x *ListCommentsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type VideoInteractionStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	LikesCount    int64                  `protobuf:"varint,2,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount int64                  `protobuf:"varint,3,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	Popularity    int64                  `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
	IsLiked       bool                   `protobuf:"varint,5,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInteractionStats) Reset() {
	*x = VideoInteractionStats{}
	mi := &file_interaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInteractionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInteractionStats) ProtoMessage() {}

func (x *VideoInteractionStats) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInteractionStats.ProtoReflect.Descriptor instead.
func (*VideoInteractionStats) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{16}
}

func (x *VideoInteractionStats) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoInteractionStats) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *VideoInteractionStats) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *VideoInteractionStats) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *VideoInteractionStats) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

// BatchGetVideoStats is used by gateway/video/feed to hydrate list/detail cards.
type BatchGetVideoStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerId      uint64                 `protobuf:"varint,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	VideoIds      []uint64               `protobuf:"varint,2,rep,packed,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoStatsReq) Reset() {
	*x = BatchGetVideoStatsReq{}
	mi := &file_interaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoStatsReq) ProtoMessage() {}

func (x *BatchGetVideoStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoStatsReq.ProtoReflect.Descriptor instead.
func (*BatchGetVideoStatsReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetVideoStatsReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *BatchGetVideoStatsReq) GetVideoIds() []uint64 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type BatchGetVideoStatsResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Stats         []*VideoInteractionStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoStatsResp) Reset() {
	*x = BatchGetVideoStatsResp{}
	mi := &file_interaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoStatsResp) ProtoMessage() {}

func (x *BatchGetVideoStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoStatsResp.ProtoReflect.Descriptor instead.
func (*BatchGetVideoStatsResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{18}
}

func (x *BatchGetVideoStatsResp) GetStats() []*VideoInteractionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type LikeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        LikeAction             `protobuf:"varint,4,opt,name=action,proto3,enum=interaction.LikeAction" json:"action,omitempty"`
	EventTime     int64                  `protobuf:"varint,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeEvent) Reset() {
	*x = LikeEvent{}
	mi := &file_interaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeEvent) ProtoMessage() {}

func (x *LikeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeEvent.ProtoReflect.Descriptor instead.
func (*LikeEvent) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{19}
}

func (x *LikeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LikeEvent) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeEvent) GetAction() LikeAction {
	if x != nil {
		return x.Action
	}
	return LikeAction_LIKE_ACTION_UNKNOWN
}

func (x *LikeEvent) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type CommentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CommentId     uint64                 `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        CommentAction          `protobuf:"varint,5,opt,name=action,proto3,enum=interaction.CommentAction" json:"action,omitempty"`
	EventTime     int64                  `protobuf:"varint,6,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentEvent) Reset() {
	*x = CommentEvent{}
	mi := &file_interaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentEvent) ProtoMessage() {}

func (x *CommentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentEvent.ProtoReflect.Descriptor instead.
func (*CommentEvent) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{20}
}

func (x *CommentEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CommentEvent) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentEvent) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentEvent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentEvent) GetAction() CommentAction {
	if x != nil {
		return x.Action
	}
	return CommentAction_COMMENT_ACTION_UNKNOWN
}

func (x *CommentEvent) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

// FlushLikeEvents can be called by a job that consumes Kafka/Redis Stream
// and wants interaction-rpc to own relation-table writes and idempotency.
type FlushLikeEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LikeEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushLikeEventsReq) Reset() {
	*x = FlushLikeEventsReq{}
	mi := &file_interaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushLikeEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushLikeEventsReq) ProtoMessage() {}

func (x *FlushLikeEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushLikeEventsReq.ProtoReflect.Descriptor instead.
func (*FlushLikeEventsReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{21}
}

func (x *FlushLikeEventsReq) GetEvents() []*LikeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type FlushLikeEventsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount   int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedEventIds []string               `protobuf:"bytes,2,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushLikeEventsResp) Reset() {
	*x = FlushLikeEventsResp{}
	mi := &file_interaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushLikeEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushLikeEventsResp) ProtoMessage() {}

func (x *FlushLikeEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushLikeEventsResp.ProtoReflect.Descriptor instead.
func (*FlushLikeEventsResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{22}
}

func (x *FlushLikeEventsResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *FlushLikeEventsResp) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

// FlushCommentEvents can be used for async comment counter/stat maintenance.
type FlushCommentEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CommentEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushCommentEventsReq) Reset() {
	*x = FlushCommentEventsReq{}
	mi := &file_interaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCommentEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCommentEventsReq) ProtoMessage() {}

func (x *FlushCommentEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCommentEventsReq.ProtoReflect.Descriptor instead.
func (*FlushCommentEventsReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{23}
}

func (x *FlushCommentEventsReq) GetEvents() []*CommentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type FlushCommentEventsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount   int64                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedEventIds []string               `protobuf:"bytes,2,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushCommentEventsResp) Reset() {
	*x = FlushCommentEventsResp{}
	mi := &file_interaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCommentEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCommentEventsResp) ProtoMessage() {}

func (x *FlushCommentEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCommentEventsResp.ProtoReflect.Descriptor instead.
func (*FlushCommentEventsResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{24}
}

func (x *FlushCommentEventsResp) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *FlushCommentEventsResp) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

// RebuildVideoInteractionStats is an internal repair API for jobs/admin tools.
type RebuildVideoInteractionStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIds      []uint64               `protobuf:"varint,1,rep,packed,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildVideoInteractionStatsReq) Reset() {
	*x = RebuildVideoInteractionStatsReq{}
	mi := &file_interaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildVideoInteractionStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildVideoInteractionStatsReq) ProtoMessage() {}

func (x *RebuildVideoInteractionStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildVideoInteractionStatsReq.ProtoReflect.Descriptor instead.
func (*RebuildVideoInteractionStatsReq) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{25}
}

func (x *RebuildVideoInteractionStatsReq) GetVideoIds() []uint64 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type RebuildVideoInteractionStatsResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Stats         []*VideoInteractionStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildVideoInteractionStatsResp) Reset() {
	*x = RebuildVideoInteractionStatsResp{}
	mi := &file_interaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildVideoInteractionStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildVideoInteractionStatsResp) ProtoMessage() {}

func (x *RebuildVideoInteractionStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildVideoInteractionStatsResp.ProtoReflect.Descriptor instead.
func (*RebuildVideoInteractionStatsResp) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{26}
}

func (x *RebuildVideoInteractionStatsResp) GetStats() []*VideoInteractionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_interaction_proto protoreflect.FileDescriptor

const file_interaction_proto_rawDesc = "" +
	"\n" +
	"\x11interaction.proto\x12\vinteraction\"\xf3\x01\n" +
	"\vCommentInfo\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"can_delete\x18\b \x01(\bR\tcanDelete\"B\n" +
	"\fLikeVideoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\"X\n" +
	"\rLikeVideoResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x14\n" +
	"\x05liked\x18\x02 \x01(\bR\x05liked\x12\x1f\n" +
	"\vlikes_count\x18\x03 \x01(\x03R\n" +
	"likesCount\"D\n" +
	"\x0eUnlikeVideoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\"Z\n" +
	"\x0fUnlikeVideoResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x14\n" +
	"\x05liked\x18\x02 \x01(\bR\x05liked\x12\x1f\n" +
	"\vlikes_count\x18\x03 \x01(\x03R\n" +
	"likesCount\"@\n" +
	"\n" +
	"IsLikedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\"#\n" +
	"\vIsLikedResp\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"_\n" +
	"\x0eLikedVideoItem\x12\x17\n" +
	"\alike_id\x18\x01 \x01(\x04R\x06likeId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x19\n" +
	"\bliked_at\x18\x03 \x01(\x03R\alikedAt\"\x9e\x01\n" +
	"\x14ListMyLikedVideosReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12*\n" +
	"\x11cursor_created_at\x18\x02 \x01(\x03R\x0fcursorCreatedAt\x12$\n" +
	"\x0ecursor_like_id\x18\x03 \x01(\x04R\fcursorLikeId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xd6\x01\n" +
	"\x15ListMyLikedVideosResp\x12>\n" +
	"\fliked_videos\x18\x01 \x03(\v2\x1b.interaction.LikedVideoItemR\vlikedVideos\x123\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03R\x13nextCursorCreatedAt\x12-\n" +
	"\x13next_cursor_like_id\x18\x03 \x01(\x04R\x10nextCursorLikeId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x9c\x01\n" +
	"\x11PublishCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x81\x01\n" +
	"\x12PublishCommentResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x122\n" +
	"\acomment\x18\x02 \x01(\v2\x18.interaction.CommentInfoR\acomment\x12%\n" +
	"\x0ecomments_count\x18\x03 \x01(\x03R\rcommentsCount\"J\n" +
	"\x10DeleteCommentReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x04R\tcommentId\"f\n" +
	"\x11DeleteCommentResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\x12%\n" +
	"\x0ecomments_count\x18\x03 \x01(\x03R\rcommentsCount\"\xbe\x01\n" +
	"\x0fListCommentsReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\x12*\n" +
	"\x11cursor_created_at\x18\x03 \x01(\x03R\x0fcursorCreatedAt\x12*\n" +
	"\x11cursor_comment_id\x18\x04 \x01(\x04R\x0fcursorCommentId\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"\xcd\x01\n" +
	"\x10ListCommentsResp\x124\n" +
	"\bcomments\x18\x01 \x03(\v2\x18.interaction.CommentInfoR\bcomments\x123\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03R\x13nextCursorCreatedAt\x123\n" +
	"\x16next_cursor_comment_id\x18\x03 \x01(\x04R\x13nextCursorCommentId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xb5\x01\n" +
	"\x15VideoInteractionStats\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1f\n" +
	"\vlikes_count\x18\x02 \x01(\x03R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\x03 \x01(\x03R\rcommentsCount\x12\x1e\n" +
	"\n" +
	"popularity\x18\x04 \x01(\x03R\n" +
	"popularity\x12\x19\n" +
	"\bis_liked\x18\x05 \x01(\bR\aisLiked\"Q\n" +
	"\x15BatchGetVideoStatsReq\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\x04R\bviewerId\x12\x1b\n" +
	"\tvideo_ids\x18\x02 \x03(\x04R\bvideoIds\"R\n" +
	"\x16BatchGetVideoStatsResp\x128\n" +
	"\x05stats\x18\x01 \x03(\v2\".interaction.VideoInteractionStatsR\x05stats\"\xaa\x01\n" +
	"\tLikeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12/\n" +
	"\x06action\x18\x04 \x01(\x0e2\x17.interaction.LikeActionR\x06action\x12\x1d\n" +
	"\n" +
	"event_time\x18\x05 \x01(\x03R\teventTime\"\xcf\x01\n" +
	"\fCommentEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\x04R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x122\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1a.interaction.CommentActionR\x06action\x12\x1d\n" +
	"\n" +
	"event_time\x18\x06 \x01(\x03R\teventTime\"D\n" +
	"\x12FlushLikeEventsReq\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.interaction.LikeEventR\x06events\"d\n" +
	"\x13FlushLikeEventsResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\x12(\n" +
	"\x10failed_event_ids\x18\x02 \x03(\tR\x0efailedEventIds\"J\n" +
	"\x15FlushCommentEventsReq\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.interaction.CommentEventR\x06events\"g\n" +
	"\x16FlushCommentEventsResp\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x03R\fsuccessCount\x12(\n" +
	"\x10failed_event_ids\x18\x02 \x03(\tR\x0efailedEventIds\">\n" +
	"\x1fRebuildVideoInteractionStatsReq\x12\x1b\n" +
	"\tvideo_ids\x18\x01 \x03(\x04R\bvideoIds\"\\\n" +
	" RebuildVideoInteractionStatsResp\x128\n" +
	"\x05stats\x18\x01 \x03(\v2\".interaction.VideoInteractionStatsR\x05stats*S\n" +
	"\n" +
	"LikeAction\x12\x17\n" +
	"\x13LIKE_ACTION_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10LIKE_ACTION_LIKE\x10\x01\x12\x16\n" +
	"\x12LIKE_ACTION_UNLIKE\x10\x02*a\n" +
	"\rCommentAction\x12\x1a\n" +
	"\x16COMMENT_ACTION_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15COMMENT_ACTION_CREATE\x10\x01\x12\x19\n" +
	"\x15COMMENT_ACTION_DELETE\x10\x022\xb6\a\n" +
	"\vInteraction\x12B\n" +
	"\tLikeVideo\x12\x19.interaction.LikeVideoReq\x1a\x1a.interaction.LikeVideoResp\x12H\n" +
	"\vUnlikeVideo\x12\x1b.interaction.UnlikeVideoReq\x1a\x1c.interaction.UnlikeVideoResp\x12<\n" +
	"\aIsLiked\x12\x17.interaction.IsLikedReq\x1a\x18.interaction.IsLikedResp\x12Z\n" +
	"\x11ListMyLikedVideos\x12!.interaction.ListMyLikedVideosReq\x1a\".interaction.ListMyLikedVideosResp\x12Q\n" +
	"\x0ePublishComment\x12\x1e.interaction.PublishCommentReq\x1a\x1f.interaction.PublishCommentResp\x12N\n" +
	"\rDeleteComment\x12\x1d.interaction.DeleteCommentReq\x1a\x1e.interaction.DeleteCommentResp\x12K\n" +
	"\fListComments\x12\x1c.interaction.ListCommentsReq\x1a\x1d.interaction.ListCommentsResp\x12]\n" +
	"\x12BatchGetVideoStats\x12\".interaction.BatchGetVideoStatsReq\x1a#.interaction.BatchGetVideoStatsResp\x12T\n" +
	"\x0fFlushLikeEvents\x12\x1f.interaction.FlushLikeEventsReq\x1a .interaction.FlushLikeEventsResp\x12]\n" +
	"\x12FlushCommentEvents\x12\".interaction.FlushCommentEventsReq\x1a#.interaction.FlushCommentEventsResp\x12{\n" +
	"\x1cRebuildVideoInteractionStats\x12,.interaction.RebuildVideoInteractionStatsReq\x1a-.interaction.RebuildVideoInteractionStatsRespB\x0fZ\r./interactionb\x06proto3"

var (
	file_interaction_proto_rawDescOnce sync.Once
	file_interaction_proto_rawDescData []byte
)

func file_interaction_proto_rawDescGZIP() []byte {
	file_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)))
	})
	return file_interaction_proto_rawDescData
}

var file_interaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_interaction_proto_goTypes = []any{
	(LikeAction)(0),                          // 0: interaction.LikeAction
	(CommentAction)(0),                       // 1: interaction.CommentAction
	(*CommentInfo)(nil),                      // 2: interaction.CommentInfo
	(*LikeVideoReq)(nil),                     // 3: interaction.LikeVideoReq
	(*LikeVideoResp)(nil),                    // 4: interaction.LikeVideoResp
	(*UnlikeVideoReq)(nil),                   // 5: interaction.UnlikeVideoReq
	(*UnlikeVideoResp)(nil),                  // 6: interaction.UnlikeVideoResp
	(*IsLikedReq)(nil),                       // 7: interaction.IsLikedReq
	(*IsLikedResp)(nil),                      // 8: interaction.IsLikedResp
	(*LikedVideoItem)(nil),                   // 9: interaction.LikedVideoItem
	(*ListMyLikedVideosReq)(nil),             // 10: interaction.ListMyLikedVideosReq
	(*ListMyLikedVideosResp)(nil),            // 11: interaction.ListMyLikedVideosResp
	(*PublishCommentReq)(nil),                // 12: interaction.PublishCommentReq
	(*PublishCommentResp)(nil),               // 13: interaction.PublishCommentResp
	(*DeleteCommentReq)(nil),                 // 14: interaction.DeleteCommentReq
	(*DeleteCommentResp)(nil),                // 15: interaction.DeleteCommentResp
	(*ListCommentsReq)(nil),                  // 16: interaction.ListCommentsReq
	(*ListCommentsResp)(nil),                 // 17: interaction.ListCommentsResp
	(*VideoInteractionStats)(nil),            // 18: interaction.VideoInteractionStats
	(*BatchGetVideoStatsReq)(nil),            // 19: interaction.BatchGetVideoStatsReq
	(*BatchGetVideoStatsResp)(nil),           // 20: interaction.BatchGetVideoStatsResp
	(*LikeEvent)(nil),                        // 21: interaction.LikeEvent
	(*CommentEvent)(nil),                     // 22: interaction.CommentEvent
	(*FlushLikeEventsReq)(nil),               // 23: interaction.FlushLikeEventsReq
	(*FlushLikeEventsResp)(nil),              // 24: interaction.FlushLikeEventsResp
	(*FlushCommentEventsReq)(nil),            // 25: interaction.FlushCommentEventsReq
	(*FlushCommentEventsResp)(nil),           // 26: interaction.FlushCommentEventsResp
	(*RebuildVideoInteractionStatsReq)(nil),  // 27: interaction.RebuildVideoInteractionStatsReq
	(*RebuildVideoInteractionStatsResp)(nil), // 28: interaction.RebuildVideoInteractionStatsResp
}
var file_interaction_proto_depIdxs = []int32{
	9,  // 0: interaction.ListMyLikedVideosResp.liked_videos:type_name -> interaction.LikedVideoItem
	2,  // 1: interaction.PublishCommentResp.comment:type_name -> interaction.CommentInfo
	2,  // 2: interaction.ListCommentsResp.comments:type_name -> interaction.CommentInfo
	18, // 3: interaction.BatchGetVideoStatsResp.stats:type_name -> interaction.VideoInteractionStats
	0,  // 4: interaction.LikeEvent.action:type_name -> interaction.LikeAction
	1,  // 5: interaction.CommentEvent.action:type_name -> interaction.CommentAction
	21, // 6: interaction.FlushLikeEventsReq.events:type_name -> interaction.LikeEvent
	22, // 7: interaction.FlushCommentEventsReq.events:type_name -> interaction.CommentEvent
	18, // 8: interaction.RebuildVideoInteractionStatsResp.stats:type_name -> interaction.VideoInteractionStats
	3,  // 9: interaction.Interaction.LikeVideo:input_type -> interaction.LikeVideoReq
	5,  // 10: interaction.Interaction.UnlikeVideo:input_type -> interaction.UnlikeVideoReq
	7,  // 11: interaction.Interaction.IsLiked:input_type -> interaction.IsLikedReq
	10, // 12: interaction.Interaction.ListMyLikedVideos:input_type -> interaction.ListMyLikedVideosReq
	12, // 13: interaction.Interaction.PublishComment:input_type -> interaction.PublishCommentReq
	14, // 14: interaction.Interaction.DeleteComment:input_type -> interaction.DeleteCommentReq
	16, // 15: interaction.Interaction.ListComments:input_type -> interaction.ListCommentsReq
	19, // 16: interaction.Interaction.BatchGetVideoStats:input_type -> interaction.BatchGetVideoStatsReq
	23, // 17: interaction.Interaction.FlushLikeEvents:input_type -> interaction.FlushLikeEventsReq
	25, // 18: interaction.Interaction.FlushCommentEvents:input_type -> interaction.FlushCommentEventsReq
	27, // 19: interaction.Interaction.RebuildVideoInteractionStats:input_type -> interaction.RebuildVideoInteractionStatsReq
	4,  // 20: interaction.Interaction.LikeVideo:output_type -> interaction.LikeVideoResp
	6,  // 21: interaction.Interaction.UnlikeVideo:output_type -> interaction.UnlikeVideoResp
	8,  // 22: interaction.Interaction.IsLiked:output_type -> interaction.IsLikedResp
	11, // 23: interaction.Interaction.ListMyLikedVideos:output_type -> interaction.ListMyLikedVideosResp
	13, // 24: interaction.Interaction.PublishComment:output_type -> interaction.PublishCommentResp
	15, // 25: interaction.Interaction.DeleteComment:output_type -> interaction.DeleteCommentResp
	17, // 26: interaction.Interaction.ListComments:output_type -> interaction.ListCommentsResp
	20, // 27: interaction.Interaction.BatchGetVideoStats:output_type -> interaction.BatchGetVideoStatsResp
	24, // 28: interaction.Interaction.FlushLikeEvents:output_type -> interaction.FlushLikeEventsResp
	26, // 29: interaction.Interaction.FlushCommentEvents:output_type -> interaction.FlushCommentEventsResp
	28, // 30: interaction.Interaction.RebuildVideoInteractionStats:output_type -> interaction.RebuildVideoInteractionStatsResp
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_interaction_proto_init() }
func file_interaction_proto_init() {
	if File_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_proto_depIdxs,
		EnumInfos:         file_interaction_proto_enumTypes,
		MessageInfos:      file_interaction_proto_msgTypes,
	}.Build()
	File_interaction_proto = out.File
	file_interaction_proto_goTypes = nil
	file_interaction_proto_depIdxs = nil
}
