// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: interaction.proto

package interaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interaction_LikeVideo_FullMethodName                    = "/interaction.Interaction/LikeVideo"
	Interaction_UnlikeVideo_FullMethodName                  = "/interaction.Interaction/UnlikeVideo"
	Interaction_IsLiked_FullMethodName                      = "/interaction.Interaction/IsLiked"
	Interaction_ListMyLikedVideos_FullMethodName            = "/interaction.Interaction/ListMyLikedVideos"
	Interaction_PublishComment_FullMethodName               = "/interaction.Interaction/PublishComment"
	Interaction_DeleteComment_FullMethodName                = "/interaction.Interaction/DeleteComment"
	Interaction_ListComments_FullMethodName                 = "/interaction.Interaction/ListComments"
	Interaction_BatchGetVideoStats_FullMethodName           = "/interaction.Interaction/BatchGetVideoStats"
	Interaction_FlushLikeEvents_FullMethodName              = "/interaction.Interaction/FlushLikeEvents"
	Interaction_FlushCommentEvents_FullMethodName           = "/interaction.Interaction/FlushCommentEvents"
	Interaction_RebuildVideoInteractionStats_FullMethodName = "/interaction.Interaction/RebuildVideoInteractionStats"
)

// InteractionClient is the client API for Interaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionClient interface {
	LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error)
	UnlikeVideo(ctx context.Context, in *UnlikeVideoReq, opts ...grpc.CallOption) (*UnlikeVideoResp, error)
	IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error)
	ListMyLikedVideos(ctx context.Context, in *ListMyLikedVideosReq, opts ...grpc.CallOption) (*ListMyLikedVideosResp, error)
	PublishComment(ctx context.Context, in *PublishCommentReq, opts ...grpc.CallOption) (*PublishCommentResp, error)
	DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
	ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error)
	BatchGetVideoStats(ctx context.Context, in *BatchGetVideoStatsReq, opts ...grpc.CallOption) (*BatchGetVideoStatsResp, error)
	FlushLikeEvents(ctx context.Context, in *FlushLikeEventsReq, opts ...grpc.CallOption) (*FlushLikeEventsResp, error)
	FlushCommentEvents(ctx context.Context, in *FlushCommentEventsReq, opts ...grpc.CallOption) (*FlushCommentEventsResp, error)
	RebuildVideoInteractionStats(ctx context.Context, in *RebuildVideoInteractionStatsReq, opts ...grpc.CallOption) (*RebuildVideoInteractionStatsResp, error)
}

type interactionClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionClient(cc grpc.ClientConnInterface) InteractionClient {
	return &interactionClient{cc}
}

func (c *interactionClient) LikeVideo(ctx context.Context, in *LikeVideoReq, opts ...grpc.CallOption) (*LikeVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeVideoResp)
	err := c.cc.Invoke(ctx, Interaction_LikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) UnlikeVideo(ctx context.Context, in *UnlikeVideoReq, opts ...grpc.CallOption) (*UnlikeVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeVideoResp)
	err := c.cc.Invoke(ctx, Interaction_UnlikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) IsLiked(ctx context.Context, in *IsLikedReq, opts ...grpc.CallOption) (*IsLikedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsLikedResp)
	err := c.cc.Invoke(ctx, Interaction_IsLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) ListMyLikedVideos(ctx context.Context, in *ListMyLikedVideosReq, opts ...grpc.CallOption) (*ListMyLikedVideosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyLikedVideosResp)
	err := c.cc.Invoke(ctx, Interaction_ListMyLikedVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) PublishComment(ctx context.Context, in *PublishCommentReq, opts ...grpc.CallOption) (*PublishCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishCommentResp)
	err := c.cc.Invoke(ctx, Interaction_PublishComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResp)
	err := c.cc.Invoke(ctx, Interaction_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) ListComments(ctx context.Context, in *ListCommentsReq, opts ...grpc.CallOption) (*ListCommentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResp)
	err := c.cc.Invoke(ctx, Interaction_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) BatchGetVideoStats(ctx context.Context, in *BatchGetVideoStatsReq, opts ...grpc.CallOption) (*BatchGetVideoStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetVideoStatsResp)
	err := c.cc.Invoke(ctx, Interaction_BatchGetVideoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) FlushLikeEvents(ctx context.Context, in *FlushLikeEventsReq, opts ...grpc.CallOption) (*FlushLikeEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushLikeEventsResp)
	err := c.cc.Invoke(ctx, Interaction_FlushLikeEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) FlushCommentEvents(ctx context.Context, in *FlushCommentEventsReq, opts ...grpc.CallOption) (*FlushCommentEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushCommentEventsResp)
	err := c.cc.Invoke(ctx, Interaction_FlushCommentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) RebuildVideoInteractionStats(ctx context.Context, in *RebuildVideoInteractionStatsReq, opts ...grpc.CallOption) (*RebuildVideoInteractionStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildVideoInteractionStatsResp)
	err := c.cc.Invoke(ctx, Interaction_RebuildVideoInteractionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServer is the server API for Interaction service.
// All implementations must embed UnimplementedInteractionServer
// for forward compatibility.
type InteractionServer interface {
	LikeVideo(context.Context, *LikeVideoReq) (*LikeVideoResp, error)
	UnlikeVideo(context.Context, *UnlikeVideoReq) (*UnlikeVideoResp, error)
	IsLiked(context.Context, *IsLikedReq) (*IsLikedResp, error)
	ListMyLikedVideos(context.Context, *ListMyLikedVideosReq) (*ListMyLikedVideosResp, error)
	PublishComment(context.Context, *PublishCommentReq) (*PublishCommentResp, error)
	DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error)
	ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error)
	BatchGetVideoStats(context.Context, *BatchGetVideoStatsReq) (*BatchGetVideoStatsResp, error)
	FlushLikeEvents(context.Context, *FlushLikeEventsReq) (*FlushLikeEventsResp, error)
	FlushCommentEvents(context.Context, *FlushCommentEventsReq) (*FlushCommentEventsResp, error)
	RebuildVideoInteractionStats(context.Context, *RebuildVideoInteractionStatsReq) (*RebuildVideoInteractionStatsResp, error)
	mustEmbedUnimplementedInteractionServer()
}

// UnimplementedInteractionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServer struct{}

func (UnimplementedInteractionServer) LikeVideo(context.Context, *LikeVideoReq) (*LikeVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeVideo not implemented")
}
func (UnimplementedInteractionServer) UnlikeVideo(context.Context, *UnlikeVideoReq) (*UnlikeVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeVideo not implemented")
}
func (UnimplementedInteractionServer) IsLiked(context.Context, *IsLikedReq) (*IsLikedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsLiked not implemented")
}
func (UnimplementedInteractionServer) ListMyLikedVideos(context.Context, *ListMyLikedVideosReq) (*ListMyLikedVideosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyLikedVideos not implemented")
}
func (UnimplementedInteractionServer) PublishComment(context.Context, *PublishCommentReq) (*PublishCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishComment not implemented")
}
func (UnimplementedInteractionServer) DeleteComment(context.Context, *DeleteCommentReq) (*DeleteCommentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedInteractionServer) ListComments(context.Context, *ListCommentsReq) (*ListCommentsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedInteractionServer) BatchGetVideoStats(context.Context, *BatchGetVideoStatsReq) (*BatchGetVideoStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetVideoStats not implemented")
}
func (UnimplementedInteractionServer) FlushLikeEvents(context.Context, *FlushLikeEventsReq) (*FlushLikeEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushLikeEvents not implemented")
}
func (UnimplementedInteractionServer) FlushCommentEvents(context.Context, *FlushCommentEventsReq) (*FlushCommentEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushCommentEvents not implemented")
}
func (UnimplementedInteractionServer) RebuildVideoInteractionStats(context.Context, *RebuildVideoInteractionStatsReq) (*RebuildVideoInteractionStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildVideoInteractionStats not implemented")
}
func (UnimplementedInteractionServer) mustEmbedUnimplementedInteractionServer() {}
func (UnimplementedInteractionServer) testEmbeddedByValue()                     {}

// UnsafeInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServer will
// result in compilation errors.
type UnsafeInteractionServer interface {
	mustEmbedUnimplementedInteractionServer()
}

func RegisterInteractionServer(s grpc.ServiceRegistrar, srv InteractionServer) {
	// If the following call panics, it indicates UnimplementedInteractionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interaction_ServiceDesc, srv)
}

func _Interaction_LikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).LikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_LikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).LikeVideo(ctx, req.(*LikeVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_UnlikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).UnlikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_UnlikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).UnlikeVideo(ctx, req.(*UnlikeVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_IsLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLikedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).IsLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_IsLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).IsLiked(ctx, req.(*IsLikedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_ListMyLikedVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyLikedVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).ListMyLikedVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_ListMyLikedVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).ListMyLikedVideos(ctx, req.(*ListMyLikedVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_PublishComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).PublishComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_PublishComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).PublishComment(ctx, req.(*PublishCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).DeleteComment(ctx, req.(*DeleteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).ListComments(ctx, req.(*ListCommentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_BatchGetVideoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetVideoStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).BatchGetVideoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_BatchGetVideoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).BatchGetVideoStats(ctx, req.(*BatchGetVideoStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_FlushLikeEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushLikeEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).FlushLikeEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_FlushLikeEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).FlushLikeEvents(ctx, req.(*FlushLikeEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_FlushCommentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushCommentEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).FlushCommentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_FlushCommentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).FlushCommentEvents(ctx, req.(*FlushCommentEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_RebuildVideoInteractionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildVideoInteractionStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).RebuildVideoInteractionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_RebuildVideoInteractionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).RebuildVideoInteractionStats(ctx, req.(*RebuildVideoInteractionStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Interaction_ServiceDesc is the grpc.ServiceDesc for Interaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaction.Interaction",
	HandlerType: (*InteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeVideo",
			Handler:    _Interaction_LikeVideo_Handler,
		},
		{
			MethodName: "UnlikeVideo",
			Handler:    _Interaction_UnlikeVideo_Handler,
		},
		{
			MethodName: "IsLiked",
			Handler:    _Interaction_IsLiked_Handler,
		},
		{
			MethodName: "ListMyLikedVideos",
			Handler:    _Interaction_ListMyLikedVideos_Handler,
		},
		{
			MethodName: "PublishComment",
			Handler:    _Interaction_PublishComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Interaction_DeleteComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _Interaction_ListComments_Handler,
		},
		{
			MethodName: "BatchGetVideoStats",
			Handler:    _Interaction_BatchGetVideoStats_Handler,
		},
		{
			MethodName: "FlushLikeEvents",
			Handler:    _Interaction_FlushLikeEvents_Handler,
		},
		{
			MethodName: "FlushCommentEvents",
			Handler:    _Interaction_FlushCommentEvents_Handler,
		},
		{
			MethodName: "RebuildVideoInteractionStats",
			Handler:    _Interaction_RebuildVideoInteractionStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
