// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: video.proto

package server

import (
	"context"

	"feedsystem-zero/apps/video/internal/logic"
	"feedsystem-zero/apps/video/internal/svc"
	"feedsystem-zero/apps/video/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 发布视频
func (s *VideoServer) PublishVideo(ctx context.Context, in *video.PublishVideoReq) (*video.PublishVideoResp, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

// 获取视频详情
func (s *VideoServer) GetVideo(ctx context.Context, in *video.GetVideoReq) (*video.GetVideoResp, error) {
	l := logic.NewGetVideoLogic(ctx, s.svcCtx)
	return l.GetVideo(in)
}

// 批量获取视频实体
func (s *VideoServer) BatchGetVideos(ctx context.Context, in *video.BatchGetVideosReq) (*video.BatchGetVideosResp, error) {
	l := logic.NewBatchGetVideosLogic(ctx, s.svcCtx)
	return l.BatchGetVideos(in)
}

// 获取作者发布的视频列表
func (s *VideoServer) ListUserVideos(ctx context.Context, in *video.ListUserVideosReq) (*video.ListUserVideosResp, error) {
	l := logic.NewListUserVideosLogic(ctx, s.svcCtx)
	return l.ListUserVideos(in)
}

// 删除视频
func (s *VideoServer) DeleteVideo(ctx context.Context, in *video.DeleteVideoReq) (*video.DeleteVideoResp, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}
