// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: feed.proto

package server

import (
	"context"

	"feedsystem-zero/apps/feed/feed"
	"feedsystem-zero/apps/feed/internal/logic"
	"feedsystem-zero/apps/feed/internal/svc"
)

type FeedServer struct {
	svcCtx *svc.ServiceContext
	feed.UnimplementedFeedServer
}

func NewFeedServer(svcCtx *svc.ServiceContext) *FeedServer {
	return &FeedServer{
		svcCtx: svcCtx,
	}
}

// 关注流：viewer 关注的所有作者的最新视频，按发布时间倒序
func (s *FeedServer) GetFollowingFeed(ctx context.Context, in *feed.GetFollowingFeedReq) (*feed.GetFollowingFeedResp, error) {
	l := logic.NewGetFollowingFeedLogic(ctx, s.svcCtx)
	return l.GetFollowingFeed(in)
}

// 推荐流：当前返回全局最新视频，未登录也可访问
func (s *FeedServer) GetRecommendFeed(ctx context.Context, in *feed.GetRecommendFeedReq) (*feed.GetRecommendFeedResp, error) {
	l := logic.NewGetRecommendFeedLogic(ctx, s.svcCtx)
	return l.GetRecommendFeed(in)
}

// 热榜：按固定分钟快照读取最近时间窗口内的热门视频
func (s *FeedServer) GetHotFeed(ctx context.Context, in *feed.GetHotFeedReq) (*feed.GetHotFeedResp, error) {
	l := logic.NewGetHotFeedLogic(ctx, s.svcCtx)
	return l.GetHotFeed(in)
}
