// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FeedVideoItem 是 Feed 候选项，只描述“哪个视频、排在什么位置”。
// 作者、标题、标签和互动统计由 gateway 分别通过 VideoRpc.BatchGetVideos 和
// InteractionRpc.BatchGetVideoStats 批量补齐，避免 Feed 服务越过自身数据边界。
type FeedVideoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,2,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix milliseconds，来自 Timeline member
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedVideoItem) Reset() {
	*x = FeedVideoItem{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedVideoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedVideoItem) ProtoMessage() {}

func (x *FeedVideoItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedVideoItem.ProtoReflect.Descriptor instead.
func (*FeedVideoItem) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedVideoItem) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *FeedVideoItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

// 关注流：读取 viewer 关注的所有作者的最新视频，按发布时间倒序分页。
// 首次请求 cursor_published_at 传 0，表示从最新开始。
// 后续请求使用上次返回的 next_cursor_published_at / next_cursor_video_id。
// 两个游标必须同时为 0 或同时大于 0；page_size 默认 20，最大 50。
type GetFollowingFeedReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViewerId          uint64                 `protobuf:"varint,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`                              // 必须由 gateway 从 JWT 解析填入
	CursorPublishedAt int64                  `protobuf:"varint,2,opt,name=cursor_published_at,json=cursorPublishedAt,proto3" json:"cursor_published_at,omitempty"` // 游标：上一页最后一条视频的发布时间毫秒
	CursorVideoId     uint64                 `protobuf:"varint,3,opt,name=cursor_video_id,json=cursorVideoId,proto3" json:"cursor_video_id,omitempty"`             // 游标：上一页最后一条视频 ID（时间相同时兜底排序）
	PageSize          int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFollowingFeedReq) Reset() {
	*x = GetFollowingFeedReq{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingFeedReq) ProtoMessage() {}

func (x *GetFollowingFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingFeedReq.ProtoReflect.Descriptor instead.
func (*GetFollowingFeedReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingFeedReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *GetFollowingFeedReq) GetCursorPublishedAt() int64 {
	if x != nil {
		return x.CursorPublishedAt
	}
	return 0
}

func (x *GetFollowingFeedReq) GetCursorVideoId() uint64 {
	if x != nil {
		return x.CursorVideoId
	}
	return 0
}

func (x *GetFollowingFeedReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowingFeedResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Items                 []*FeedVideoItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursorPublishedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_published_at,json=nextCursorPublishedAt,proto3" json:"next_cursor_published_at,omitempty"`
	NextCursorVideoId     uint64                 `protobuf:"varint,3,opt,name=next_cursor_video_id,json=nextCursorVideoId,proto3" json:"next_cursor_video_id,omitempty"`
	HasMore               bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetFollowingFeedResp) Reset() {
	*x = GetFollowingFeedResp{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingFeedResp) ProtoMessage() {}

func (x *GetFollowingFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingFeedResp.ProtoReflect.Descriptor instead.
func (*GetFollowingFeedResp) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingFeedResp) GetItems() []*FeedVideoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFollowingFeedResp) GetNextCursorPublishedAt() int64 {
	if x != nil {
		return x.NextCursorPublishedAt
	}
	return 0
}

func (x *GetFollowingFeedResp) GetNextCursorVideoId() uint64 {
	if x != nil {
		return x.NextCursorVideoId
	}
	return 0
}

func (x *GetFollowingFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 推荐流：面向未登录、冷启动或无关注对象的用户，当前返回全局最新视频。
// 后续若引入会动态变分的热度榜，应使用独立榜单快照/游标策略，不直接复用发布时间游标。
// viewer_id 允许为 0，表示未登录访问。
// 两个游标必须同时为 0 或同时大于 0；page_size 默认 20，最大 50。
type GetRecommendFeedReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViewerId          uint64                 `protobuf:"varint,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 0 表示未登录
	CursorPublishedAt int64                  `protobuf:"varint,2,opt,name=cursor_published_at,json=cursorPublishedAt,proto3" json:"cursor_published_at,omitempty"`
	CursorVideoId     uint64                 `protobuf:"varint,3,opt,name=cursor_video_id,json=cursorVideoId,proto3" json:"cursor_video_id,omitempty"`
	PageSize          int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRecommendFeedReq) Reset() {
	*x = GetRecommendFeedReq{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedReq) ProtoMessage() {}

func (x *GetRecommendFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedReq.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedReq) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendFeedReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *GetRecommendFeedReq) GetCursorPublishedAt() int64 {
	if x != nil {
		return x.CursorPublishedAt
	}
	return 0
}

func (x *GetRecommendFeedReq) GetCursorVideoId() uint64 {
	if x != nil {
		return x.CursorVideoId
	}
	return 0
}

func (x *GetRecommendFeedReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRecommendFeedResp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Items                 []*FeedVideoItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursorPublishedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_published_at,json=nextCursorPublishedAt,proto3" json:"next_cursor_published_at,omitempty"`
	NextCursorVideoId     uint64                 `protobuf:"varint,3,opt,name=next_cursor_video_id,json=nextCursorVideoId,proto3" json:"next_cursor_video_id,omitempty"`
	HasMore               bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetRecommendFeedResp) Reset() {
	*x = GetRecommendFeedResp{}
	mi := &file_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedResp) ProtoMessage() {}

func (x *GetRecommendFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedResp.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedResp) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendFeedResp) GetItems() []*FeedVideoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRecommendFeedResp) GetNextCursorPublishedAt() int64 {
	if x != nil {
		return x.NextCursorPublishedAt
	}
	return 0
}

func (x *GetRecommendFeedResp) GetNextCursorVideoId() uint64 {
	if x != nil {
		return x.NextCursorVideoId
	}
	return 0
}

func (x *GetRecommendFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x04feed\"M\n" +
	"\rFeedVideoItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12!\n" +
	"\fpublished_at\x18\x02 \x01(\x03R\vpublishedAt\"\xa7\x01\n" +
	"\x13GetFollowingFeedReq\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\x04R\bviewerId\x12.\n" +
	"\x13cursor_published_at\x18\x02 \x01(\x03R\x11cursorPublishedAt\x12&\n" +
	"\x0fcursor_video_id\x18\x03 \x01(\x04R\rcursorVideoId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xc6\x01\n" +
	"\x14GetFollowingFeedResp\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.feed.FeedVideoItemR\x05items\x127\n" +
	"\x18next_cursor_published_at\x18\x02 \x01(\x03R\x15nextCursorPublishedAt\x12/\n" +
	"\x14next_cursor_video_id\x18\x03 \x01(\x04R\x11nextCursorVideoId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xa7\x01\n" +
	"\x13GetRecommendFeedReq\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\x04R\bviewerId\x12.\n" +
	"\x13cursor_published_at\x18\x02 \x01(\x03R\x11cursorPublishedAt\x12&\n" +
	"\x0fcursor_video_id\x18\x03 \x01(\x04R\rcursorVideoId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xc6\x01\n" +
	"\x14GetRecommendFeedResp\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.feed.FeedVideoItemR\x05items\x127\n" +
	"\x18next_cursor_published_at\x18\x02 \x01(\x03R\x15nextCursorPublishedAt\x12/\n" +
	"\x14next_cursor_video_id\x18\x03 \x01(\x04R\x11nextCursorVideoId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore2\x9c\x01\n" +
	"\x04Feed\x12I\n" +
	"\x10GetFollowingFeed\x12\x19.feed.GetFollowingFeedReq\x1a\x1a.feed.GetFollowingFeedResp\x12I\n" +
	"\x10GetRecommendFeed\x12\x19.feed.GetRecommendFeedReq\x1a\x1a.feed.GetRecommendFeedRespB\bZ\x06./feedb\x06proto3"

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData []byte
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)))
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feed_proto_goTypes = []any{
	(*FeedVideoItem)(nil),        // 0: feed.FeedVideoItem
	(*GetFollowingFeedReq)(nil),  // 1: feed.GetFollowingFeedReq
	(*GetFollowingFeedResp)(nil), // 2: feed.GetFollowingFeedResp
	(*GetRecommendFeedReq)(nil),  // 3: feed.GetRecommendFeedReq
	(*GetRecommendFeedResp)(nil), // 4: feed.GetRecommendFeedResp
}
var file_feed_proto_depIdxs = []int32{
	0, // 0: feed.GetFollowingFeedResp.items:type_name -> feed.FeedVideoItem
	0, // 1: feed.GetRecommendFeedResp.items:type_name -> feed.FeedVideoItem
	1, // 2: feed.Feed.GetFollowingFeed:input_type -> feed.GetFollowingFeedReq
	3, // 3: feed.Feed.GetRecommendFeed:input_type -> feed.GetRecommendFeedReq
	2, // 4: feed.Feed.GetFollowingFeed:output_type -> feed.GetFollowingFeedResp
	4, // 5: feed.Feed.GetRecommendFeed:output_type -> feed.GetRecommendFeedResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
