// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: apps/feed/feed.proto

package feed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Feed_GetFollowingFeed_FullMethodName = "/feed.Feed/GetFollowingFeed"
	Feed_GetRecommendFeed_FullMethodName = "/feed.Feed/GetRecommendFeed"
	Feed_GetHotFeed_FullMethodName       = "/feed.Feed/GetHotFeed"
)

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Feed 服务
type FeedClient interface {
	// 关注流：viewer 关注的所有作者的最新视频，按发布时间倒序
	GetFollowingFeed(ctx context.Context, in *GetFollowingFeedReq, opts ...grpc.CallOption) (*GetFollowingFeedResp, error)
	// 推荐流：当前返回全局最新视频，未登录也可访问
	GetRecommendFeed(ctx context.Context, in *GetRecommendFeedReq, opts ...grpc.CallOption) (*GetRecommendFeedResp, error)
	// 热榜：按固定分钟快照读取最近时间窗口内的热门视频
	GetHotFeed(ctx context.Context, in *GetHotFeedReq, opts ...grpc.CallOption) (*GetHotFeedResp, error)
}

type feedClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedClient(cc grpc.ClientConnInterface) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) GetFollowingFeed(ctx context.Context, in *GetFollowingFeedReq, opts ...grpc.CallOption) (*GetFollowingFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingFeedResp)
	err := c.cc.Invoke(ctx, Feed_GetFollowingFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetRecommendFeed(ctx context.Context, in *GetRecommendFeedReq, opts ...grpc.CallOption) (*GetRecommendFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendFeedResp)
	err := c.cc.Invoke(ctx, Feed_GetRecommendFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedClient) GetHotFeed(ctx context.Context, in *GetHotFeedReq, opts ...grpc.CallOption) (*GetHotFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotFeedResp)
	err := c.cc.Invoke(ctx, Feed_GetHotFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
// All implementations must embed UnimplementedFeedServer
// for forward compatibility.
//
// Feed 服务
type FeedServer interface {
	// 关注流：viewer 关注的所有作者的最新视频，按发布时间倒序
	GetFollowingFeed(context.Context, *GetFollowingFeedReq) (*GetFollowingFeedResp, error)
	// 推荐流：当前返回全局最新视频，未登录也可访问
	GetRecommendFeed(context.Context, *GetRecommendFeedReq) (*GetRecommendFeedResp, error)
	// 热榜：按固定分钟快照读取最近时间窗口内的热门视频
	GetHotFeed(context.Context, *GetHotFeedReq) (*GetHotFeedResp, error)
	mustEmbedUnimplementedFeedServer()
}

// UnimplementedFeedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedServer struct{}

func (UnimplementedFeedServer) GetFollowingFeed(context.Context, *GetFollowingFeedReq) (*GetFollowingFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingFeed not implemented")
}
func (UnimplementedFeedServer) GetRecommendFeed(context.Context, *GetRecommendFeedReq) (*GetRecommendFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendFeed not implemented")
}
func (UnimplementedFeedServer) GetHotFeed(context.Context, *GetHotFeedReq) (*GetHotFeedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotFeed not implemented")
}
func (UnimplementedFeedServer) mustEmbedUnimplementedFeedServer() {}
func (UnimplementedFeedServer) testEmbeddedByValue()              {}

// UnsafeFeedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedServer will
// result in compilation errors.
type UnsafeFeedServer interface {
	mustEmbedUnimplementedFeedServer()
}

func RegisterFeedServer(s grpc.ServiceRegistrar, srv FeedServer) {
	// If the following call panics, it indicates UnimplementedFeedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Feed_ServiceDesc, srv)
}

func _Feed_GetFollowingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetFollowingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetFollowingFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetFollowingFeed(ctx, req.(*GetFollowingFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetRecommendFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetRecommendFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetRecommendFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetRecommendFeed(ctx, req.(*GetRecommendFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Feed_GetHotFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetHotFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Feed_GetHotFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetHotFeed(ctx, req.(*GetHotFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Feed_ServiceDesc is the grpc.ServiceDesc for Feed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Feed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feed.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowingFeed",
			Handler:    _Feed_GetFollowingFeed_Handler,
		},
		{
			MethodName: "GetRecommendFeed",
			Handler:    _Feed_GetRecommendFeed_Handler,
		},
		{
			MethodName: "GetHotFeed",
			Handler:    _Feed_GetHotFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/feed/feed.proto",
}
