// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package socialclient

import (
	"context"

	"feedsystem-zero/apps/social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchIsFollowingReq  = social.BatchIsFollowingReq
	BatchIsFollowingResp = social.BatchIsFollowingResp
	FollowRelation       = social.FollowRelation
	FollowReq            = social.FollowReq
	FollowResp           = social.FollowResp
	FollowingState       = social.FollowingState
	IsFollowingReq       = social.IsFollowingReq
	IsFollowingResp      = social.IsFollowingResp
	ListFollowersReq     = social.ListFollowersReq
	ListFollowersResp    = social.ListFollowersResp
	ListFollowingsReq    = social.ListFollowingsReq
	ListFollowingsResp   = social.ListFollowingsResp
	UnfollowReq          = social.UnfollowReq
	UnfollowResp         = social.UnfollowResp

	Social interface {
		// 关注
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 取关
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		// 判断是否关注
		IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error)
		// 展示粉丝
		ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error)
		// 展示关注
		ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error)
		// 批量获取关注信息
		BatchIsFollowing(ctx context.Context, in *BatchIsFollowingReq, opts ...grpc.CallOption) (*BatchIsFollowingResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 关注
func (m *defaultSocial) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

// 取关
func (m *defaultSocial) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

// 判断是否关注
func (m *defaultSocial) IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsFollowing(ctx, in, opts...)
}

// 展示粉丝
func (m *defaultSocial) ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.ListFollowers(ctx, in, opts...)
}

// 展示关注
func (m *defaultSocial) ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.ListFollowings(ctx, in, opts...)
}

// 批量获取关注信息
func (m *defaultSocial) BatchIsFollowing(ctx context.Context, in *BatchIsFollowingReq, opts ...grpc.CallOption) (*BatchIsFollowingResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.BatchIsFollowing(ctx, in, opts...)
}
