// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package socialclient

import (
	"context"

	"feedsystem-zero/apps/social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowReq          = social.FollowReq
	FollowResp         = social.FollowResp
	UnfollowReq        = social.UnfollowReq
	UnfollowResp       = social.UnfollowResp
	IsFollowingReq     = social.IsFollowingReq
	IsFollowingResp    = social.IsFollowingResp
	FollowRelation     = social.FollowRelation
	ListFollowersReq   = social.ListFollowersReq
	ListFollowersResp  = social.ListFollowersResp
	ListFollowingsReq  = social.ListFollowingsReq
	ListFollowingsResp = social.ListFollowingsResp

	Social interface {
		Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error)
		IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error)
		ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error)
		ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

func (m *defaultSocial) Follow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultSocial) Unfollow(ctx context.Context, in *UnfollowReq, opts ...grpc.CallOption) (*UnfollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultSocial) IsFollowing(ctx context.Context, in *IsFollowingReq, opts ...grpc.CallOption) (*IsFollowingResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsFollowing(ctx, in, opts...)
}

func (m *defaultSocial) ListFollowers(ctx context.Context, in *ListFollowersReq, opts ...grpc.CallOption) (*ListFollowersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.ListFollowers(ctx, in, opts...)
}

func (m *defaultSocial) ListFollowings(ctx context.Context, in *ListFollowingsReq, opts ...grpc.CallOption) (*ListFollowingsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.ListFollowings(ctx, in, opts...)
}
