CREATE TABLE IF NOT EXISTS file_assets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  file_hash VARCHAR(128) NOT NULL,
  file_type VARCHAR(32) NOT NULL DEFAULT 'video',
  url VARCHAR(512) NOT NULL,
  storage_path VARCHAR(1024) NOT NULL,
  size BIGINT NOT NULL DEFAULT 0,
  ref_count BIGINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_file_hash (file_hash),
  UNIQUE KEY uk_url (url),
  KEY idx_status_ref (status, ref_count, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
