// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: notification.proto

package notificationclient

import (
	"context"

	"feedsystem-zero/apps/notification/notification"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUnreadCountReq            = notification.GetUnreadCountReq
	GetUnreadCountResp           = notification.GetUnreadCountResp
	ListNotificationsReq         = notification.ListNotificationsReq
	ListNotificationsResp        = notification.ListNotificationsResp
	MarkAllNotificationsReadReq  = notification.MarkAllNotificationsReadReq
	MarkAllNotificationsReadResp = notification.MarkAllNotificationsReadResp
	MarkNotificationReadReq      = notification.MarkNotificationReadReq
	MarkNotificationReadResp     = notification.MarkNotificationReadResp
	NotificationInfo             = notification.NotificationInfo

	Notification interface {
		ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
		GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
		MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error)
		MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadReq, opts ...grpc.CallOption) (*MarkAllNotificationsReadResp, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultNotification) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

func (m *defaultNotification) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.MarkNotificationRead(ctx, in, opts...)
}

func (m *defaultNotification) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadReq, opts ...grpc.CallOption) (*MarkAllNotificationsReadResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.MarkAllNotificationsRead(ctx, in, opts...)
}
