// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommentInfo struct {
	Commentid uint64 `json:"comment_id"`
	Videoid   uint64 `json:"video_id"`
	Userid    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Content   string `json:"content"`
	Createdat int64  `json:"created_at"`
	Updatedat int64  `json:"updated_at"`
	Candelete bool   `json:"can_delete"`
}

type CompleteVideoUploadReq struct {
	Uploadid    string `json:"upload_id"`
	Filename    string `json:"filename"`
	Filehash    string `json:"file_hash"`
	Filesize    int64  `json:"file_size"`
	Totalchunks int64  `json:"total_chunks"`
}

type CompleteVideoUploadResp struct {
	Msg      string `json:"msg"`
	Playurl  string `json:"play_url"`
	Filehash string `json:"file_hash"`
}

type DeleteCommentReq struct {
	Commentid uint64 `path:"comment_id"`
}

type DeleteCommentResp struct {
	Msg           string `json:"msg"`
	Deleted       bool   `json:"deleted"`
	Commentscount int64  `json:"comments_count"`
}

type DeleteVideoReq struct {
	Videoid uint64 `path:"id"`
}

type DeleteVideoResp struct {
	Msg string `json:"msg"`
}

type FollowRelationInfo struct {
	Relationid        uint64         `json:"relation_id"`
	User              SocialUserInfo `json:"user"`
	Followedat        int64          `json:"followed_at"`
	Viewerisfollowing bool           `json:"viewer_is_following"`
}

type FollowReq struct {
	Targetuserid uint64 `path:"id"`
}

type FollowResp struct {
	Msg      string `json:"msg"`
	Followed bool   `json:"followed"`
}

type GetFollowingFeedReq struct {
	Cursorpublishedat int64  `form:"cursor_published_at,optional"`
	Cursorvideoid     uint64 `form:"cursor_video_id,optional"`
	Pagesize          int64  `form:"page_size,optional"`
}

type GetFollowingFeedResp struct {
	Videos                []VideoInfo `json:"videos"`
	Nextcursorpublishedat int64       `json:"next_cursor_published_at"`
	Nextcursorvideoid     uint64      `json:"next_cursor_video_id"`
	Hasmore               bool        `json:"has_more"`
}

type GetProfileReq struct {
}

type GetProfileResp struct {
	Userid          uint64 `json:"user_id"`
	Username        string `json:"username"`
	Email           string `json:"email"`
	Avatarurl       string `json:"avatar_url"`
	Bio             string `json:"bio"`
	Followerscount  int64  `json:"followers_count"`
	Followingscount int64  `json:"followings_count"`
}

type GetRecommendFeedReq struct {
	Cursorpublishedat int64  `form:"cursor_published_at,optional"`
	Cursorvideoid     uint64 `form:"cursor_video_id,optional"`
	Pagesize          int64  `form:"page_size,optional"`
}

type GetRecommendFeedResp struct {
	Videos                []VideoInfo `json:"videos"`
	Nextcursorpublishedat int64       `json:"next_cursor_published_at"`
	Nextcursorvideoid     uint64      `json:"next_cursor_video_id"`
	Hasmore               bool        `json:"has_more"`
}

type GetVideoReq struct {
	Videoid uint64 `path:"id"`
}

type GetVideoResp struct {
	Video VideoInfo `json:"video"`
}

type InitVideoUploadReq struct {
	Filename    string `json:"filename"`
	Filehash    string `json:"file_hash"`
	Filesize    int64  `json:"file_size"`
	Chunksize   int64  `json:"chunk_size,optional"`
	Totalchunks int64  `json:"total_chunks,optional"`
}

type InitVideoUploadResp struct {
	Msg                 string  `json:"msg"`
	Uploadid            string  `json:"upload_id"`
	Needupload          bool    `json:"need_upload"`
	Needchunk           bool    `json:"need_chunk"`
	Playurl             string  `json:"play_url"`
	Uploadedchunks      []int64 `json:"uploaded_chunks"`
	Chunksize           int64   `json:"chunk_size"`
	Chunkthresholdbytes int64   `json:"chunk_threshold_bytes"`
}

type IsFollowingReq struct {
	Targetuserid uint64 `path:"id"`
}

type IsFollowingResp struct {
	Following bool `json:"following"`
}

type IsLikedReq struct {
	Videoid uint64 `path:"id"`
}

type IsLikedResp struct {
	Liked bool `json:"liked"`
}

type LikeVideoReq struct {
	Videoid uint64 `path:"id"`
}

type LikeVideoResp struct {
	Msg        string `json:"msg"`
	Liked      bool   `json:"liked"`
	Likescount int64  `json:"likes_count"`
}

type LikedVideoInfo struct {
	Likeid  uint64    `json:"like_id"`
	Likedat int64     `json:"liked_at"`
	Video   VideoInfo `json:"video"`
}

type ListCommentsReq struct {
	Videoid         uint64 `path:"id"`
	Cursorcreatedat int64  `form:"cursor_created_at,optional"`
	Cursorcommentid uint64 `form:"cursor_comment_id,optional"`
	Pagesize        int64  `form:"page_size,optional"`
}

type ListCommentsResp struct {
	Comments            []CommentInfo `json:"comments"`
	Nextcursorcreatedat int64         `json:"next_cursor_created_at"`
	Nextcursorcommentid uint64        `json:"next_cursor_comment_id"`
	Hasmore             bool          `json:"has_more"`
}

type ListFollowersReq struct {
	Userid          uint64 `path:"id"`
	Cursorupdatedat int64  `form:"cursor_updated_at,optional"`
	Cursorfollowid  uint64 `form:"cursor_follow_id,optional"`
	Pagesize        int64  `form:"page_size,optional"`
}

type ListFollowersResp struct {
	Followers           []FollowRelationInfo `json:"followers"`
	Nextcursorupdatedat int64                `json:"next_cursor_updated_at"`
	Nextcursorfollowid  uint64               `json:"next_cursor_follow_id"`
	Hasmore             bool                 `json:"has_more"`
}

type ListFollowingsReq struct {
	Userid          uint64 `path:"id"`
	Cursorupdatedat int64  `form:"cursor_updated_at,optional"`
	Cursorfollowid  uint64 `form:"cursor_follow_id,optional"`
	Pagesize        int64  `form:"page_size,optional"`
}

type ListFollowingsResp struct {
	Followings          []FollowRelationInfo `json:"followings"`
	Nextcursorupdatedat int64                `json:"next_cursor_updated_at"`
	Nextcursorfollowid  uint64               `json:"next_cursor_follow_id"`
	Hasmore             bool                 `json:"has_more"`
}

type ListMyLikedVideosReq struct {
	Cursorcreatedat int64  `form:"cursor_created_at,optional"`
	Cursorlikeid    uint64 `form:"cursor_like_id,optional"`
	Pagesize        int64  `form:"page_size,optional"`
}

type ListMyLikedVideosResp struct {
	Likedvideos         []LikedVideoInfo `json:"liked_videos"`
	Nextcursorcreatedat int64            `json:"next_cursor_created_at"`
	Nextcursorlikeid    uint64           `json:"next_cursor_like_id"`
	Hasmore             bool             `json:"has_more"`
}

type ListUserVideosReq struct {
	Authorid        uint64 `path:"author_id"`
	Cursorcreatedat int64  `form:"cursor_created_at,optional"`
	Cursorvideoid   uint64 `form:"cursor_video_id,optional"`
	Pagesize        int64  `form:"page_size,optional"`
}

type ListUserVideosResp struct {
	Videos              []VideoInfo `json:"videos"`
	Nextcursorcreatedat int64       `json:"next_cursor_created_at"`
	Nextcursorvideoid   uint64      `json:"next_cursor_video_id"`
	Hasmore             bool        `json:"has_more"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutReq struct {
}

type LogoutResp struct {
	Msg string `json:"msg"`
}

type PublishCommentReq struct {
	Videoid   uint64 `path:"id"`
	Content   string `json:"content"`
	Requestid string `json:"request_id,optional"`
}

type PublishCommentResp struct {
	Msg           string      `json:"msg"`
	Comment       CommentInfo `json:"comment"`
	Commentscount int64       `json:"comments_count"`
}

type PublishVideoReq struct {
	Title       string   `json:"title"`
	Description string   `json:"description,optional"`
	Playurl     string   `json:"play_url"`
	Coverurl    string   `json:"cover_url"`
	Tags        []string `json:"tags,optional"`
	Requestid   string   `json:"request_id,optional"`
}

type PublishVideoResp struct {
	Msg   string    `json:"msg"`
	Video VideoInfo `json:"video"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Username     string `json:"username"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	Verification string `json:"verification"`
}

type RegisterResp struct {
	Msg string `json:"msg"`
}

type SocialUserInfo struct {
	Userid    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Avatarurl string `json:"avatar_url"`
	Bio       string `json:"bio"`
}

type UnfollowReq struct {
	Targetuserid uint64 `path:"id"`
}

type UnfollowResp struct {
	Msg        string `json:"msg"`
	Unfollowed bool   `json:"unfollowed"`
}

type UnlikeVideoReq struct {
	Videoid uint64 `path:"id"`
}

type UnlikeVideoResp struct {
	Msg        string `json:"msg"`
	Liked      bool   `json:"liked"`
	Likescount int64  `json:"likes_count"`
}

type UpdateProfileReq struct {
	Username  string  `json:"username,optional"`
	Avatarurl string  `json:"avatar_url,optional"`
	Bio       *string `json:"bio,optional"`
}

type UpdateProfileResp struct {
	Msg string `json:"msg"`
}

type UploadCoverResp struct {
	Msg      string `json:"msg"`
	Coverurl string `json:"cover_url"`
}

type UploadVideoChunkReq struct {
	Uploadid   string `form:"upload_id"`
	Chunkindex int64  `form:"chunk_index"`
	Chunkhash  string `form:"chunk_hash"`
}

type UploadVideoChunkResp struct {
	Msg            string  `json:"msg"`
	Uploadid       string  `json:"upload_id"`
	Chunkindex     int64   `json:"chunk_index"`
	Uploadedchunks []int64 `json:"uploaded_chunks"`
}

type UploadVideoResp struct {
	Msg     string `json:"msg"`
	Playurl string `json:"play_url"`
}

type VerificationReq struct {
	Email string `json:"email"`
}

type VerificationResp struct {
	Verification string `json:"verification"`
}

type VideoInfo struct {
	Videoid        uint64   `json:"video_id"`
	Authorid       uint64   `json:"author_id"`
	Authorusername string   `json:"author_username"`
	Title          string   `json:"title"`
	Description    string   `json:"description"`
	Playurl        string   `json:"play_url"`
	Coverurl       string   `json:"cover_url"`
	Likescount     int64    `json:"likes_count"`
	Commentscount  int64    `json:"comments_count"`
	Popularity     int64    `json:"popularity"`
	Status         int32    `json:"status"`
	Createdat      int64    `json:"created_at"`
	Updatedat      int64    `json:"updated_at"`
	Isliked        bool     `json:"is_liked"`
	Tags           []string `json:"tags"`
}

type VideoUploadStatusReq struct {
	Uploadid string `form:"upload_id"`
	Filehash string `form:"file_hash,optional"`
}

type VideoUploadStatusResp struct {
	Uploadid       string  `json:"upload_id"`
	Uploadedchunks []int64 `json:"uploaded_chunks"`
	Totalchunks    int64   `json:"total_chunks"`
	Completed      bool    `json:"completed"`
	Playurl        string  `json:"play_url"`
}

// ============================ 热榜 ============================

type HotFeedVideo struct {
	Video    VideoInfo `json:"video"`
	Hotscore float64   `json:"hot_score"`
	Rank     int64     `json:"rank"`
}

type GetHotFeedReq struct {
	Snapshotat int64 `form:"snapshot_at,optional"`
	Offset     int64 `form:"offset,optional"`
	Pagesize   int64 `form:"page_size,optional"`
}

type GetHotFeedResp struct {
	Items      []HotFeedVideo `json:"items"`
	Snapshotat int64          `json:"snapshot_at"`
	Nextoffset int64          `json:"next_offset"`
	Hasmore    bool           `json:"has_more"`
}

// ======================= 批量关注状态查询 =======================

type BatchIsFollowingReq struct {
	Targetuserids []uint64 `json:"target_user_ids"`
}

type FollowingStateInfo struct {
	Targetuserid uint64 `json:"target_user_id"`
	Following    bool   `json:"following"`
}

type BatchIsFollowingResp struct {
	States []FollowingStateInfo `json:"states"`
}

// =========================== 通知 ==============================

type NotificationActor struct {
	Userid    uint64 `json:"user_id"`
	Username  string `json:"username"`
	Avatarurl string `json:"avatar_url"`
}

type NotificationVideo struct {
	Videoid  uint64 `json:"video_id"`
	Title    string `json:"title"`
	Coverurl string `json:"cover_url"`
}

type NotificationItem struct {
	Notificationid uint64             `json:"notification_id"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	Actor          NotificationActor  `json:"actor"`
	Video          *NotificationVideo `json:"video,omitempty"`
	Commentid      uint64             `json:"comment_id,omitempty"`
	Occurredat     int64              `json:"occurred_at"`
	Readat         int64              `json:"read_at"`
}

type ListNotificationsReq struct {
	Cursoroccurredat     int64  `form:"cursor_occurred_at,optional"`
	Cursornotificationid uint64 `form:"cursor_notification_id,optional"`
	Pagesize             int64  `form:"page_size,optional"`
}

type ListNotificationsResp struct {
	Notifications            []NotificationItem `json:"notifications"`
	Nextcursoroccurredat     int64              `json:"next_cursor_occurred_at"`
	Nextcursornotificationid uint64             `json:"next_cursor_notification_id"`
	Hasmore                  bool               `json:"has_more"`
}

type GetUnreadCountReq struct{}

type GetUnreadCountResp struct {
	Unreadcount int64 `json:"unread_count"`
}

type MarkNotificationReadReq struct {
	Notificationid uint64 `path:"id"`
}

type MarkNotificationReadResp struct {
	Changed bool `json:"changed"`
}

type MarkAllNotificationsReadReq struct{}

type MarkAllNotificationsReadResp struct {
	Changedcount int64 `json:"changed_count"`
}
