// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: video.proto

package video

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VideoInfo 是视频详情和列表共用的数据结构。
// status: 1=正常, 2=作者删除, 3=审核下架。
type VideoInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	AuthorId       uint64                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,3,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PlayUrl        string                 `protobuf:"bytes,6,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	LikesCount     int64                  `protobuf:"varint,8,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount  int64                  `protobuf:"varint,9,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	Popularity     int64                  `protobuf:"varint,10,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Status         int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix milliseconds
	UpdatedAt      int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix milliseconds
	IsLiked        bool                   `protobuf:"varint,14,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	Tags           []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoInfo) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *VideoInfo) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *VideoInfo) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *VideoInfo) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *VideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VideoInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *VideoInfo) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *VideoInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// PublishVideo 只发布视频元数据。
// 视频文件和封面文件由 gateway 上传后生成 play_url/cover_url。
type PublishVideoReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthorId       uint64                 `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,2,opt,name=author_username,json=authorUsername,proto3" json:"author_username,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PlayUrl        string                 `protobuf:"bytes,5,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	RequestId      string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishVideoReq) Reset() {
	*x = PublishVideoReq{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoReq) ProtoMessage() {}

func (x *PublishVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoReq.ProtoReflect.Descriptor instead.
func (*PublishVideoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *PublishVideoReq) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PublishVideoReq) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *PublishVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishVideoReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishVideoReq) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *PublishVideoReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PublishVideoReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PublishVideoReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PublishVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Video         *VideoInfo             `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVideoResp) Reset() {
	*x = PublishVideoResp{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVideoResp) ProtoMessage() {}

func (x *PublishVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVideoResp.ProtoReflect.Descriptor instead.
func (*PublishVideoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *PublishVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PublishVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

// 获取视频信息
// viewer_id 为 0 表示未登录访问；非 0 时后续可以补 is_liked。
type GetVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ViewerId      uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoReq) Reset() {
	*x = GetVideoReq{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReq) ProtoMessage() {}

func (x *GetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReq.ProtoReflect.Descriptor instead.
func (*GetVideoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetVideoReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

type GetVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoInfo             `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResp) Reset() {
	*x = GetVideoResp{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResp) ProtoMessage() {}

func (x *GetVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResp.ProtoReflect.Descriptor instead.
func (*GetVideoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoResp) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

// 查询作者发布的视频列表。
// 首次请求 cursor_created_at/cursor_video_id 传 0。
// 后续请求使用上次返回的 next_cursor_created_at/next_cursor_video_id。
type ListUserVideosReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorId        uint64                 `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ViewerId        uint64                 `protobuf:"varint,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,3,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"` // Unix milliseconds
	CursorVideoId   uint64                 `protobuf:"varint,4,opt,name=cursor_video_id,json=cursorVideoId,proto3" json:"cursor_video_id,omitempty"`
	PageSize        int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUserVideosReq) Reset() {
	*x = ListUserVideosReq{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserVideosReq) ProtoMessage() {}

func (x *ListUserVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserVideosReq.ProtoReflect.Descriptor instead.
func (*ListUserVideosReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserVideosReq) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ListUserVideosReq) GetViewerId() uint64 {
	if x != nil {
		return x.ViewerId
	}
	return 0
}

func (x *ListUserVideosReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListUserVideosReq) GetCursorVideoId() uint64 {
	if x != nil {
		return x.CursorVideoId
	}
	return 0
}

func (x *ListUserVideosReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserVideosResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Videos              []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"` // Unix milliseconds
	NextCursorVideoId   uint64                 `protobuf:"varint,3,opt,name=next_cursor_video_id,json=nextCursorVideoId,proto3" json:"next_cursor_video_id,omitempty"`
	HasMore             bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListUserVideosResp) Reset() {
	*x = ListUserVideosResp{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserVideosResp) ProtoMessage() {}

func (x *ListUserVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserVideosResp.ProtoReflect.Descriptor instead.
func (*ListUserVideosResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserVideosResp) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListUserVideosResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListUserVideosResp) GetNextCursorVideoId() uint64 {
	if x != nil {
		return x.NextCursorVideoId
	}
	return 0
}

func (x *ListUserVideosResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// DeleteVideo 采用软删除。
// operator_id 必须由 gateway 从 JWT 中解析后填入，不能信任前端传用户 ID。
type DeleteVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	OperatorId    uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoReq) Reset() {
	*x = DeleteVideoReq{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoReq) ProtoMessage() {}

func (x *DeleteVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoReq.ProtoReflect.Descriptor instead.
func (*DeleteVideoReq) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVideoReq) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DeleteVideoReq) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResp) Reset() {
	*x = DeleteVideoResp{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResp) ProtoMessage() {}

func (x *DeleteVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResp.ProtoReflect.Descriptor instead.
func (*DeleteVideoResp) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVideoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\"\xc9\x03\n" +
	"\tVideoInfo\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x04R\bauthorId\x12'\n" +
	"\x0fauthor_username\x18\x03 \x01(\tR\x0eauthorUsername\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bplay_url\x18\x06 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vlikes_count\x18\b \x01(\x03R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\t \x01(\x03R\rcommentsCount\x12\x1e\n" +
	"\n" +
	"popularity\x18\n" +
	" \x01(\x03R\n" +
	"popularity\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bis_liked\x18\x0e \x01(\bR\aisLiked\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\"\xdb\x01\n" +
	"\x0fPublishVideoReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x04R\bauthorId\x12'\n" +
	"\x0fauthor_username\x18\x02 \x01(\tR\x0eauthorUsername\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bplay_url\x18\x05 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"L\n" +
	"\x10PublishVideoResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12&\n" +
	"\x05video\x18\x02 \x01(\v2\x10.video.VideoInfoR\x05video\"E\n" +
	"\vGetVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\"6\n" +
	"\fGetVideoResp\x12&\n" +
	"\x05video\x18\x01 \x01(\v2\x10.video.VideoInfoR\x05video\"\xbe\x01\n" +
	"\x11ListUserVideosReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x04R\bauthorId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\x04R\bviewerId\x12*\n" +
	"\x11cursor_created_at\x18\x03 \x01(\x03R\x0fcursorCreatedAt\x12&\n" +
	"\x0fcursor_video_id\x18\x04 \x01(\x04R\rcursorVideoId\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"\xbf\x01\n" +
	"\x12ListUserVideosResp\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x123\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03R\x13nextCursorCreatedAt\x12/\n" +
	"\x14next_cursor_video_id\x18\x03 \x01(\x04R\x11nextCursorVideoId\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"L\n" +
	"\x0eDeleteVideoReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\"#\n" +
	"\x0fDeleteVideoResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\x82\x02\n" +
	"\x05Video\x12?\n" +
	"\fPublishVideo\x12\x16.video.PublishVideoReq\x1a\x17.video.PublishVideoResp\x123\n" +
	"\bGetVideo\x12\x12.video.GetVideoReq\x1a\x13.video.GetVideoResp\x12E\n" +
	"\x0eListUserVideos\x12\x18.video.ListUserVideosReq\x1a\x19.video.ListUserVideosResp\x12<\n" +
	"\vDeleteVideo\x12\x15.video.DeleteVideoReq\x1a\x16.video.DeleteVideoRespB\tZ\a./videob\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_video_proto_goTypes = []any{
	(*VideoInfo)(nil),          // 0: video.VideoInfo
	(*PublishVideoReq)(nil),    // 1: video.PublishVideoReq
	(*PublishVideoResp)(nil),   // 2: video.PublishVideoResp
	(*GetVideoReq)(nil),        // 3: video.GetVideoReq
	(*GetVideoResp)(nil),       // 4: video.GetVideoResp
	(*ListUserVideosReq)(nil),  // 5: video.ListUserVideosReq
	(*ListUserVideosResp)(nil), // 6: video.ListUserVideosResp
	(*DeleteVideoReq)(nil),     // 7: video.DeleteVideoReq
	(*DeleteVideoResp)(nil),    // 8: video.DeleteVideoResp
}
var file_video_proto_depIdxs = []int32{
	0, // 0: video.PublishVideoResp.video:type_name -> video.VideoInfo
	0, // 1: video.GetVideoResp.video:type_name -> video.VideoInfo
	0, // 2: video.ListUserVideosResp.videos:type_name -> video.VideoInfo
	1, // 3: video.Video.PublishVideo:input_type -> video.PublishVideoReq
	3, // 4: video.Video.GetVideo:input_type -> video.GetVideoReq
	5, // 5: video.Video.ListUserVideos:input_type -> video.ListUserVideosReq
	7, // 6: video.Video.DeleteVideo:input_type -> video.DeleteVideoReq
	2, // 7: video.Video.PublishVideo:output_type -> video.PublishVideoResp
	4, // 8: video.Video.GetVideo:output_type -> video.GetVideoResp
	6, // 9: video.Video.ListUserVideos:output_type -> video.ListUserVideosResp
	8, // 10: video.Video.DeleteVideo:output_type -> video.DeleteVideoResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
