// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: account.proto

package accountclient

import (
	"context"

	"feedsystem-zero/apps/account/account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetProfilesReq  = account.BatchGetProfilesReq
	BatchGetProfilesResp = account.BatchGetProfilesResp
	GetProfileReq        = account.GetProfileReq
	GetProfileResp       = account.GetProfileResp
	LoginReq             = account.LoginReq
	LoginResp            = account.LoginResp
	LogoutReq            = account.LogoutReq
	LogoutResp           = account.LogoutResp
	PublicProfile        = account.PublicProfile
	RefreshTokenReq      = account.RefreshTokenReq
	RefreshTokenResp     = account.RefreshTokenResp
	RegisterReq          = account.RegisterReq
	RegisterResp         = account.RegisterResp
	UpdateProfileReq     = account.UpdateProfileReq
	UpdateProfileResp    = account.UpdateProfileResp
	VerificationReq      = account.VerificationReq
	VerificationResp     = account.VerificationResp

	Account interface {
		// 验证码
		SendVerification(ctx context.Context, in *VerificationReq, opts ...grpc.CallOption) (*VerificationResp, error)
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// 刷新token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		// 查用户
		GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error)
		// 批量查询公开用户资料
		BatchGetProfiles(ctx context.Context, in *BatchGetProfilesReq, opts ...grpc.CallOption) (*BatchGetProfilesResp, error)
		// 更新用户信息
		UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

// 验证码
func (m *defaultAccount) SendVerification(ctx context.Context, in *VerificationReq, opts ...grpc.CallOption) (*VerificationResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.SendVerification(ctx, in, opts...)
}

// 注册
func (m *defaultAccount) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultAccount) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 登出
func (m *defaultAccount) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 刷新token
func (m *defaultAccount) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 查用户
func (m *defaultAccount) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

// 批量查询公开用户资料
func (m *defaultAccount) BatchGetProfiles(ctx context.Context, in *BatchGetProfilesReq, opts ...grpc.CallOption) (*BatchGetProfilesResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.BatchGetProfiles(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultAccount) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}
